### ISSUE TITLE
Version filters on exports is returning blank files

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#1020]
What's happening is when exporting forms using form version filters and you switch between different versions, the file that is exported is empty as the version value being passed is blank.

**Comment by mberg** [comment]
Awesome is this fixed now? We should let Andrew pinney know if it is

**Comment by bmalina** [comment]
@ukanga can we add an option to export all data by default and have someone select the different version they want in the advanced options? 

What is happening now is one will have to export the data in different versions but using the current version of the form.

### Example
 - Upload an XLS form and collect a few records (Version 1).
 - Remove certain fields in the XLS form, replace the form and collect more records. (Version 2 - current version).
 - When exporting data from version 1 of the form, the fields in current version (Version 2) will be used meaning the removed fields will not be displayed. This does not make sense. The export should show all the fields in its form version.
