### ISSUE TITLE
_submisssion_time metadata doesn't appear as a selectable option when creating a filtered dataset

### ISSUE THREAD

**Issue by dkwamboka** [onaio/onadata#1023]
### Environment 
Production

### Expected behaviour
When creating a filtered dataset, all present fields in your dataset should appear and you should be able to select  whichever fields you would like displayed in your new dataset.

You should be able to have the option of including the **_submission_time**  field in your filtered dataset.

### Actual behaviour
The  **_submission_time** field is not present for selection when creating a filtered dataset.

### Steps to reproduce the behaviour

- Create a form and upload it in a project on Ona
- Submit records to this form
- View records in Table View, the **Submission time** column is present
- Export the data, the **_submission_time** field is also present
- Create a filtered dataset from this form, you find that you do not have the option to include the **_submission_time** field

**Comment by ukanga** [comment]
Reading this it seems like this needs to be migrated to [zebra issues](https://github.com/onaio/zebra/issues). `_submission_time` is the time the submission reached the server.

**Comment by dkwamboka** [comment]
Closed and re-opened under  zebra issues.
