### ISSUE TITLE
Note field types are exporting in Excel/Googlesheets file types in repeat groups

### ISSUE THREAD

**Issue by msschroeder** [onaio/onadata#1037]
What is occurring: Note field types are exporting in Excel/Googlesheet file types in repeat groups in XLSForms. Other file types are exporting as expected (i.e. CSV)

What is expected: Note field types should not be exporting in the repeat groups for any file type

To replicate this issue: 
Create a form with a repeat group and a note field within the group. 
Export the data with data collected.

Example project:
https://ona.io/onasupport/3571/209406

**Comment by msschroeder** [comment]
@ukanga @moshthepitt I need to test this again. As a previous fix, may have addressed this.

**Comment by moshthepitt** [comment]
@msschroeder has a previous fix addressed this?

**Comment by msschroeder** [comment]
@moshthepitt No, the previous fix did not address the fact that notes are still exporting in the CSV data.

**Comment by moshthepitt** [comment]
@msschroeder just to be clear, this is handled correctly in CSV but incorrectly in Excel and Google Sheets?

**Comment by msschroeder** [comment]
@moshthepitt It is still not being handled correctly in CSV
