### ISSUE TITLE
Org's free plan private project transfer not working as expected 

### ISSUE THREAD

**Issue by KipSigei** [onaio/onadata#1044]
### Environment (local, stage, preview, production)
All
### Expected behavior
- [ ] If the private project count on profile endpoint is 0, private projects shouldn't be transferred to that -
account
- [ ] After transferring a project,  ownership of the account transferring should be revoked
### Actual behavior
- If the private project count on profile endpoint is 0, private projects are being transferred to that account
- The projects also exist in projects endpoint on both account A and B after transferring
### Steps to reproduce the behavior
- Create two separate accounts, say A and B
- On account A, create an org and change to the free/legacy plan i.e private projects/forms are not allowed
- Create a number private projects on account B
- Try transferring them to the org created in account A. You will notice that there is not limit applied to the number of private projects being transferred to the org and also the projects still persist in account B.
---
### Implementation plan

- 
- 
-

**Comment by ukanga** [comment]
duplicate and wrong repo
