### ISSUE TITLE
Org's free plan private project transfer with form limit not working as expected

### ISSUE THREAD

**Issue by msschroeder** [onaio/onadata#1046]
### Environment (local, stage, preview, production)
All
### Expected behavior
- [ ]Private project should not be allowed to transfer from one account to another if the total count of active forms with the active forms in transferred project is greater than account limit.

### Actual behavior
- Private project can be transferred from one account to another even if the total count of active forms with the active forms in transferred project is greater than account limit.

### Steps to reproduce the behavior
- Create two separate accounts, say A and B
- On account A, create an org and leave with a new (01-2017) free pricing plan
- Create a private project with a large number of forms on account B
- Try transferring them to the org created in account A. You will notice that there is not limit applied to the number of forms transferred in the private projects.
 
---
### Implementation plan

- 
- 
-

**Comment by ukanga** [comment]
Created in the wrong repo.
