### ISSUE TITLE
Add ability to redirect to a given URL after logging out of API

### ISSUE THREAD

**Issue by KipSigei** [onaio/onadata#1062]
if `return_url` or `next` param is provided, it should redirect to it after logging out of API

**Comment by cagulas** [comment]
@ukanga This is for the Brazil work, so we have end of July (31st) for the project end date.

**Comment by ukanga** [comment]
On the oauth page, show username, add option to switch user, which essentially logs out a user redirect them to login then back to oauth page.

**Comment by ukanga** [comment]
This was fixed by #1079
