### ISSUE TITLE
API is returning enketo url with the value 'false' on some edits

### ISSUE THREAD

**Issue by KipSigei** [onaio/onadata#1072]
API Endpoint: /data/[pk]/[dataid]/enketo

Expected:
 Return status 400 with an appropriate failure message if a submission edit URL is not present.

**Comment by ukanga** [comment]
This happened because we were posting a too large body to Enketo than what it was configured to receive. In this case, we need to handle HTTP status codes >= 400 and return an appropriate error message to the user.
