### ISSUE TITLE
Users without permission to public project cannot export data

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#1077]
### Environment (local, stage, preview, production)
All

### Expected behavior
- A public project should allow users without permission to it to export and download data
- Exporting data when it’s public should not require authentication

### Actual behavior
- A public project does not allow users without permission to it to export and download data

### Steps to reproduce the behavior
Access a public project and try to download data
---

### Implementation plan

- 
- 
- 

### Blocking or related [onadata](https://github.com/onaio/onadata/) issues

I'm tagging @KipSigei here so that when the issue is done, he can be alerted

**Comment by moshthepitt** [comment]
Fix seems to not work as expected.

**Comment by moshthepitt** [comment]
Please dont close this.  I'll close it.

**Comment by JohnMwashuma** [comment]
@moshthepitt If the authorization header is present the api returns an empty list
