### ISSUE TITLE
Select multiple with choice filter results in string values in SAV export

### ISSUE THREAD

**Issue by msschroeder** [onaio/onadata#1087]
### Environment (local, stage, preview, production)
production

### Expected behavior
All select multiple questions answers in split columns should be displayed as numeric values (i.e. 0/1).

### Actual behavior
All select multiple questions answers in split columns are displayed as string values (i.e. True/False) instead of numeric values (i.e. 0/1) if the question has a choice filter.

### Steps to reproduce the behavior
1. Create an XLSForm with one select_multiple question with no choice filter and one select_multiple question with a choice filter. An [example form](https://docs.google.com/spreadsheets/d/1aOPa_CSbXN0dZiECjKu2nKz6VmNBv_LXAkJZ3y80kS8/edit?usp=sharing).
2. Upload the form to ona.io. Fill in a few data records and submit.
3. Download a SAV export and upload to https://www.savreader.com/ to see the export results for the select_multiple questions with and without a choice filter.

### Implementation plan

- 
- 
-

**Comment by moshthepitt** [comment]
![savreader online datafile viewer sav](https://user-images.githubusercontent.com/372073/29320957-8fbf314c-81e1-11e7-9e4a-a331db5fc0f0.png)

@msschroeder I can't seem to be able to replicate this.  Are you still getting the same erroneous result?
