### ISSUE TITLE
Throw appropriate exception when clicking on edit record link for a record that is still being edited on another tab

### ISSUE THREAD

**Issue by KipSigei** [onaio/onadata#1090]
When a user clicks on the edit record link when editing is still in progress in another tab, show an appropriate error message or raise a proper exception.

![image](https://user-images.githubusercontent.com/19689992/29304867-3189bea0-819e-11e7-8a10-ea972b464db9.png)

**Comment by moshthepitt** [comment]
@KipSigei this was fixed on stage and now needs to be implemented in zebra, see: https://github.com/onaio/zebra/issues/5177

I'll go ahead and close this - yes?
