### ISSUE TITLE
How to handle empty data submissions for encrypted forms

### ISSUE THREAD

**Issue by msschroeder** [onaio/onadata#1113]
Currently, a client is using a encrypted form to collect data. Sometimes, the submissions are empty resulting in error when decrypting the data using ODK Briefcase (Missing files: submission.xml.enc)

The data exports are automated making it difficult to simply manually delete the one submission causing the error as each time the data is automatically exported, the empty submission is included.

What would be the best way to prevent the client from receiving - having an empty submission included in exports? 

Possible solutions presented by client: at point of data submission or data export.

This could mean:

- Ensuring that only complete data submissions are accepted by the server and that the submission can be resent

- Preventing the meta data associated with these submissions from conflicting with the available media files, therefore ensuring that the data is always available even if the media file is lost.

**Comment by pld** [comment]
Why are the submissions empty?

**Comment by msschroeder** [comment]
It appears that not all portions of the data are submitted from ODK Collect to the Ona server. This appears to be an issue from the sending side. If they are not received by the system, there is nothing we can do from our end. We can recommend that the user ensures that the data is submitted before deleting, but many people using encrypted forms also use the delete after submission. 

According to the client, once the data is "submitted" to Ona, the data is deleted from ODK Collect and therefore, to resubmit is not an option. The client has agreed loss of one data line is okay. So the question remains, how do we deal with a record when there is no submission.xml.enc associated?

**Comment by ukanga** [comment]
There is nothing to do on the server side for this, all attachments were not received. The client will need to recover the missing attachment from the ODK folder of the device that sent the submission. If the client cannot recover the missing files, then the client will need to remove the submission folder with missing attachments and attempt to export the data.
