### ISSUE TITLE
Output results in the spec results format

### ISSUE THREAD

**Issue by pld** [onaio/onadata#1117]
Add an export endpoint that outputs form data in the format described here, (bottom) https://github.com/FLOIP/flow-results#example

For now I'm OK using a the mimetype, `json+floip`

Users should be able to hit the existing export endpoints requesting this mimetype and get back their data in FLOIP format

**Comment by pld** [comment]
@ukanga not sure the best approach, how's this start? https://github.com/onaio/onadata/compare/1117-output-in-floip?expand=1

**Comment by nateMJ** [comment]
@pld The link you provided here doesn't work
Did you mean this https://github.com/FLOIP/flow-results#example ?

**Comment by pld** [comment]
Yep, I've updated the description
