### ISSUE TITLE
Disable data submission for users with Can View role

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#1159]
**Environment (local, stage, preview, production)**

Production

**Expected behavior**

Users with Can View role should not be able to submit data.

**Actual behavior**

Users with Can View role are able to submit data to forms from ODK Collect which shouldn't be the case.

**Steps to reproduce the behavior**

1. Add your account to a project in a different account and assign `Can View` role to your account.
2. Download a form on ODK Collect then submit data. The record is submitted successfully.

**Comment by faith-mutua** [comment]
@Wambere @ukanga this issue seems to have been fixed by this zebra issue https://github.com/onaio/zebra/issues/5227.

**Comment by ukanga** [comment]
Seems it is not possible to recreate this issue.
