### ISSUE TITLE
Filtering with media_all_received does not work on encrypted forms data

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1166]
https://api.ona.io/api/v1/data/249826?media_all_received=true

It seems that for encrypted forms, trying to filter data using media_all_received does not work.

**Comment by Wambere** [comment]
Cannot recreate

**Comment by moshthepitt** [comment]
@Wambere what about here https://api.ona.io/api/v1/data/249826?media_all_received=true
