### ISSUE TITLE
FLOIP doc updates and tests

### ISSUE THREAD

**Issue by pld** [onaio/onadata#1175]
* [x] fix backquotes in info box
  * https://api.ona.io/static/docs/submissions.html#submit-a-floip-xform-submission
* [x] update docs to mention which question types in FLOIP Ona supports
  * https://api.ona.io/static/docs/forms.html#publish-floip-results-data-package
* [x] test that Ona understands these formats, update code if it doesn't:
  * [x] `select_many`
  * [x] `geopoint`
  * [x] `datetime`
  * [x] `date`
  * [x] `time`

**Comment by nateMJ** [comment]
@pld `open` question type isn't supported

**Comment by pld** [comment]
OK, that's OK, we only committed to supported the subset that are compatible w/XForms
