### ISSUE TITLE
Error when pulling data from a XLSForm with repeat groups

### ISSUE THREAD

**Issue by bmalina** [onaio/onadata#1181]
**Environment:** Production

![image](https://user-images.githubusercontent.com/20789710/32650550-46e56d5c-c60f-11e7-9fd5-52a17fdc059c.png)

**Comment by faith-mutua** [comment]
@Wambere I am still getting the above error when pulling data from a repeat group. I am using these forms to test; [pull_repeat](https://docs.google.com/spreadsheets/d/1i2RS-Yh7NNINON9HMa3Fn0EZA3hUARs0bs0qtdblHic/edit?usp=sharing) which is pulling data from [child4](https://docs.google.com/spreadsheets/d/11gRco4O8Yv7yFg_Zc8OG423jORxEnokIkd14KiFXLDc/edit?usp=sharing).
