### ISSUE TITLE
Can not export data in filtered datasets

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/onadata#1184]
The exports list for a filtered dataset form returns an empty list for an authenticated user who does not have permission to it's parent form.

`curl -X GET https://api.ona.io/api/v1/export?xform=249870 -u <username>:<password>
output: [ ]`

**Comment by JohnMwashuma** [comment]
https://github.com/onaio/zebra/issues/5258

**Comment by JohnMwashuma** [comment]
#5258

**Comment by JohnMwashuma** [comment]
onaio/zebra#5258

**Comment by JohnMwashuma** [comment]
onaio/zebra#5258

**Comment by ukanga** [comment]
Seems not an issue any more
