### ISSUE TITLE
Reapply roles when meta permissions are enabled to existing users

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1192]
When adding a user to a project for forms with meta permissions, the `role-minor` is usually selected,  For existing users, this role is not reapplied and still maintain the full permissions for the `role` rather than taking on `data-role`.

**Comment by ukanga** [comment]
From the look of things, this seems to be happening as expected.

**Comment by faith-mutua** [comment]
@ukanga this is working as expected.
