### ISSUE TITLE
If form has version, include it in formList XML

### ISSUE THREAD

**Issue by lognaturel** [onaio/onadata#1195]
Since Collect 1.12, form updates are highlighted from the Get Blank Forms screen. 

Users of Ona noticed a crash -- https://forum.opendatakit.org/t/odk-collect-1-12-1-stops-when-logging-in-to-get-blank-form/11132 This is because forms that have a version defined don't also include that version in the formList XML as described at http://docs.opendatakit.org/openrosa-form-list/#successful-response-document

That crash is fixed on the Collect side but the lack of version means updates to media files can't be detected.

**Comment by ukanga** [comment]
Re-opening because there was unexpected behaviour when using ODK Briefcase. Changes were reverted in https://github.com/onaio/onadata/pull/1215
