### ISSUE TITLE
Improve performance of online-only webform views

### ISSUE THREAD

**Issue by MartijnR** [onaio/onadata#1207]
Hi Ona,

I wanted to provide 2 suggestions to make online-only views faster today (and even more so in the near future, due to some caching mechanism changes in Enketo to provide [more advanced support for dynamic external data](https://github.com/kobotoolbox/enketo-express/issues/906)):

1. Let `<manifestUrl>` be empty in the`/formList` document if the form has no media/data. This avoids Enketo having to check a manifestUrl without content (saves about 500ms of a typical form load after the caching changes)

2. Optimize response times of /formList and manifest requests, e.g. by aggressive caching and by supporting the formID query parameter in `/formList?formID=widgets` which is (an obscure) part of the OpenRosa Form Discovery Spec and Enketo has been including it for years.

**Comment by ukanga** [comment]
Thanks @MartijnR for the tips, we will look into it.

**Comment by Wambere** [comment]
closed by #1245 #1246
