### ISSUE TITLE
[Django 2.0] Migrate to Django version 2.0

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1257]
Django 2.0 is here and we need to upgrade.  Here are the [release notes](https://docs.djangoproject.com/en/2.0/releases/2.0/).

Specifically we need to:

1. Identify breaking changes from django 1.11 to django 2.0 and fix these
1. make all the code compatible with python3 (Django 2.0 supports only python 3)

Specific issues that address various parts of the above will be linked to this issue for tracking.

We are starting with issues that can be implemented while still on Django 1.11 and thereafter will move to Python3/Django2

**Comment by pld** [comment]
https://github.com/arogozhnikov/python3_with_pleasure

**Comment by moshthepitt** [comment]
http://python3porting.com/improving.html

**Comment by moshthepitt** [comment]
Related to, and blocked by: https://github.com/onaio/onadata/pull/1295

**Comment by moshthepitt** [comment]
http://python-future.org/compatible_idioms.html
