### ISSUE TITLE
[Django 2.0] Improved queryset iterator

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1260]
Django 2.0 now ships with an improved queryset iterator that accepts a "chunk size" parameter.

We should use this in all areas that we need a queryset iterator and remove the custom one that we have in ```onadata.libs.utils.model_tools ```

More: https://docs.djangoproject.com/en/2.0/ref/models/querysets/

Related: #1257

**Comment by bmarika** [comment]
Handled here https://github.com/onaio/onadata/pull/1559
