### ISSUE TITLE
Image links not included in an export as excel and csv zipped file

### ISSUE THREAD

**Issue by samwata** [onaio/onadata#1265]
### Environment (local, stage, preview, production)
production
### Expected behavior
When exporting the data as excel file/csv zipped file, the image links is included in the export.
### Actual behavior
When exporting data as excel/csv zipped file, the image links is not included in the export, even if the advanced option to include the links of the image is selected. It only includes the name of the file assigned when uploaded.
### Steps to reproduce the behavior
1. Upload a form with an image. Example form can be found via this [link](https://docs.google.com/spreadsheets/d/12Nw6aemfaFTuB4oX9Vb779ITwzZf8m4Tkt6_QKcxWz4/edit?usp=sharing).
2. Create a few submission
3. On the form's Overview page, prepare the data export as excel/csv zipped file with the advanced option include image links selected.
4. The export does not include the image links
---

### Implementation plan
., the image links is not included in the export.
---

**Comment by Wambere** [comment]
Fixed by #1266

**Comment by ukanga** [comment]
This has to do with existing attachments having the name field being null. Nothing to be fixed in code.
