### ISSUE TITLE
SVG media labels support?

### ISSUE THREAD

**Issue by MartijnR** [onaio/onadata#1268]
Both Enketo and (future) ODK Collect support these fancy widgets now: 
https://enke.to/::imgmap

I'd like to add this widget to the [demo widgets form](https://enke.to/::widgets) which is hosted on Ona. So I wanted to check if you'll be adding SVG support in the near future, or if I should move my demo forms to KoBo ;).

See more here: https://blog.enketo.org/image-map/

**Comment by MartijnR** [comment]
I noticed it's possibly to upload an SVG (though not for regular users probably).

In this case the issue is with serving the correct content-type:

<img width="663" alt="screen shot 2018-02-21 at 1 50 52 pm" src="https://user-images.githubusercontent.com/627350/36504629-657009e4-170e-11e8-80c8-729267917a66.png">

**Comment by mberg** [comment]
Hey hey @MartijnR let's not be crazy now! We'll get this sorted ;)

**Comment by MartijnR** [comment]
The tactic worked! ;)
