### ISSUE TITLE
API query failed return HTML page 

### ISSUE THREAD

**Issue by RemiDesgrange** [onaio/onadata#1292]
I query the api with this request (ona.io site) : 
``` 
https://api.ona.io/api/v1/data/<myID>?query={"_submission_time":{"$gt":"2018-02-12"}}
```
and it gave me this error : 
![image](https://user-images.githubusercontent.com/13271765/37584259-13bee484-2b55-11e8-9ade-dcebd5629f4f.png)

The problem here is not that I misformed my request but the return value which is HTML and not json erro payload.

**Comment by ukanga** [comment]
All 500 errors will likely always be HTML pages, in this case, it seems we may not be interpreting the query correctly. 

I will suggest you use the `date_created` field which is exactly the same as the `_submission_time` field. See https://api.ona.io/static/docs/data.html#query-submitted-data-of-a-specific-form-using-date-created for details.

**Comment by RemiDesgrange** [comment]
Ok good to know ;-)

**Comment by ukanga** [comment]
Created an issue for the 500 error, see #1293.

**Comment by pld** [comment]
Should they be returning HTML pages? It seems somewhat odd. But I guess if
a content-type is not specified it's reasonable
