### ISSUE TITLE
Add Form Schema Endpoint

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1296]
@pld @ukanga 

#### OSM Fields
It seems that there is no way for us to get the expected OSM fields from just the XForm spec.  The XForm spec will point to an OSM field and the OSM sheet on the XForm spec can give us information about some expected OSM fields but the actual fields that come with the data are only known to ona.io when it inspects the OSM attachments.

After processing OSM attachments, ona.io stores the OSM data in a model called OsmData, which has a JSON field called `tags` where the OSM data is stored in key:value pairs.  These key value pairs are what we ideally want to include in our Druid dimensions spec - and we don't have a good way to get them at the moment.

#### A new form schema API endpoint?
I propose that we add am API endpoint to ona.io that takes a form pk and returns a [schema](http://json-schema.org/) of the form's fields.  These fields will be generated by ona.io using the XLS form, the OSM data, and any other sources that would helps us get a complete and as-accurate-as-possible schema of the form's fields.

Do you think this is a good idea?

**Comment by moshthepitt** [comment]
Related: https://github.com/onaio/canopy/pull/38

**Comment by pld** [comment]
This sounds like a very good idea, I didn't realize that at the moment the XForm didn't give you sufficient information to build a schema for the data.

An additional feature to consider, but not a necessity, would to have this endpoint return some variations on the schema that are needed for some data stores. E.g. Druid cannot handle nested data so we would have to flatten the schema by prefixing nested fields their parents name plus an underscore. On the other hand, an argument against doing this is that it requires the data to be transformed as well, so it does semantically belong in an ETL layer not the raw API.

**Comment by ukanga** [comment]
What schema is being proposed here?

We do have a schema at `/api/v1/forms/[pk]/form.json`, if you want he schema in XML simply use `.xml`. The JSON Schema looks like the one below:
```JSON
{
    "name": "tutorial",
    "title": "tutorial",
    "type": "survey",
    "default_language": "default",
    "id_string": "tutorial",
    "sms_keyword": "tutorial",
    "children": [
        {
            "type": "text",
            "name": "name",
            "label": "Where?"
        },
        {
            "type": "integer",
            "name": "age",
            "label": "How many People Present?"
        },
        {
            "type": "geopoint",
            "name": "gps",
            "label": "your GPS coordinates."
        },
        {
            "type": "image",
            "name": "picture",
            "label": "Photo?"
        },
        {
            "type": "group",
            "children": [
                {
                    "bind": {
                        "calculate": "'65ad45b67b7745559f89efd4137fd8ef'"
                    },
                    "type": "calculate",
                    "name": "uuid"
                }
            ],
            "name": "formhub"
        }
    ]
}
````
