### ISSUE TITLE
HTTP Error 401 For Formbuilder

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1373]
This is happening on stage-api when using the python-2-3 branch.

**Comment by pld** [comment]
Could be JWT encoding related

On Wed, Apr 18, 2018 at 10:12 AM, Kelvin Jayanoris <notifications@github.com

**Comment by moshthepitt** [comment]
This turned out to be related to a Zebra deployment problem.

**Comment by ivermac** [comment]
@moshthepitt Should we close this now?

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/playbooks/pull/778
