### ISSUE TITLE
Add endpoint for monthly submissions counter

### ISSUE THREAD

**Issue by Wambere** [onaio/onadata#1406]

**Comment by ukanga** [comment]
@Wambere What will this endpoint look like?

**Comment by Wambere** [comment]
I'm adding this to the Userprofile viewset. It will return the total number of submissions made to all the profiles' private forms. And it will be accessed through http://api.ona.io/api/v1/profiles/{username}/monthly_submissions

This will replace both the monthly_submissions and the monthly_submissions_counter currently in the Userprofile endpoint. 

Part of solution for #1380

**Comment by Wambere** [comment]
Replaced by https://github.com/onaio/pricing/issues/217
