### ISSUE TITLE
Add auto-created filtered data sets

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1429]
For the ILRI Kaznet project we need to auto-create filtered data sets based on [submission reviews](https://github.com/onaio/onadata/issues/1428).

We will need 3 auto-created filtered data sets based on the three submission review statuses:

- approved
- rejected
- pending review

This feature should not be generally available, there should be a setting at the form or project or organization level that turns it on/off.

---

This feature depends on and is blocked by #1428

**Comment by pld** [comment]
Why does this need to be in onadata, can't the Kaznet app do this? Like when you register a form in ona w/Kaznet it can hit the API to create the filtered datasets

**Comment by moshthepitt** [comment]
Yes you're right,
