### ISSUE TITLE
Delete users with formbuilder connections

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1445]
When an onadata user who has data in the [form builder app](https://github.com/onaio/kpi) is deleted, the deletion will fail until you first delete the user's details in the form builder app.

We should add a way to delete the user's form builder data just before deleting the user from onadata

**Comment by pld** [comment]
Can add please details to this issue describing why you can't remove an Ona user without removing their data in formbuilder first? I think the fix here may be to allow deletion without requiring deletion from form builder

**Comment by moshthepitt** [comment]
On the KPI app, the ExtraUserDetail model (https://github.com/onaio/kpi/blob/onaio/hub/models.py) we have:

```python
class ExtraUserDetail(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='extra_details')
    data = JSONField(default={})

    def __unicode__(self):
        return '{}\'s data: {}'.format(self.user.__unicode__(), repr(self.data))
```

This app uses the same database as Onadata.  And if an onadata user is referenced by the ExtraUserDetail.user field, that relation **must** be removed first before an Onadata user can be deleted, otherwise you get something like:

```sh
Key (id)=(00000) is still referenced from table "hub_extrauserdetail".
```

**Comment by pld** [comment]
can we solve this w/a pre-delete hook?

**Comment by moshthepitt** [comment]
@pld Yes we can.

Thoughts on that approach @ukanga?

**Comment by moshthepitt** [comment]
There might be other models in the KPI app that need this treatment
