### ISSUE TITLE
Add password changed field to userprofile metadata

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1454]
It is useful to let an API consumer know when a user's password was last changed.  Let us add a `last_password_edit` field to the user profile metadata that communicates it.

### Context

The Kaznet API needs to know if a user changed their password via ona.io so that the Kaznet mobile app can anticipate and prevent ODK authentication issues by forcing users to provide their new password.

**Comment by pld** [comment]
This sounds OK as long as it is not public

**Comment by moshthepitt** [comment]
Fixed in #1456

**Comment by moshthepitt** [comment]
Related: https://github.com/onaio/kaznet-web/issues/184

**Comment by moshthepitt** [comment]
This fix was undone here: https://github.com/onaio/onadata/issues/1467

@lincmba ^^
