### ISSUE TITLE
Option to remove prefixed group name isn't working occasionally for certain cases

### ISSUE THREAD

**Issue by dkwamboka** [onaio/onadata#1476]
### Environment (local, stage, preview, production)
Production

### Expected behaviour
When you select the option that your data shouldn't be exported with prefixed group names, no group names should appear.

### Actual behavior
The group names appear for questions within more than 3 groups, for complex forms. This can be replicated occasionally, and not all forms show this behaviour.

### Steps to reproduce the behavior
This is the[ link](https://stage.ona.io/kwambox/208) to a public project on stage that contains a small section of the affected area of a clients form.
This is the Enketo [link](https://enketo-stage.ona.io/x/#pTDLMxVM).

When you export data as Excel or CSV, selecting the option to not have the group names, they still persists for some questions e.g: **Consent_Yes/REFUG_LEG/REGISTRATION_SERVICES/**

---

### Implementation plan

- 
- 
- 

### Blocking or related [onadata](https://github.com/onaio/onadata/) issues

**Comment by faith-mutua** [comment]
@dkwamboka I have managed to replicate the issue on a smaller form. This seems to be happening to
 **select_multiple** questions in two instances, 

1. When the questions are within 2 or more groups and have either a relevant condition or choice_filter applied to them. When I remove the relevance and choice_filter then export data without the group names, the prefixes are removed from the export. 
2. The other instance is when the **select_multiple** questions are as explained in instance 1 and data is exported with select multiple answers split into separate columns. 
This [form](https://ona.io/qastuff/64825/347348) has select_multiple questions with both relevance and choice_filter, [this one](https://ona.io/qastuff/64825/347346) with only choice_filter and [this one](https://ona.io/qastuff/64825/347339) without. 

**NB** All forms are public.

**Comment by lincmba** [comment]
This issue appears to have been fixed. 
New forms are not affected by this. A solution to old forms would be reuploading the forms, i.e replacing the forms with the same forms. 

@faith-mutua confirm this.
