### ISSUE TITLE
Onadata form Exports Not Working

### ISSUE THREAD

**Issue by Kirembu** [onaio/onadata#1481]
Hi,

Everything else seems to be working perfectly, except data/report export.
Under "Form Data" click on any type of report.. I've tried with "csv-report".

Click on "New Report"
The report seems to be "Pending.." indefinitely.

I'm not very familiar with RabbitMQ but it seems to be well set up.

Are there any caveats when it comes to report export that I could have missed?

**Comment by chlarsen** [comment]
Greeting,
The same happens in my case. RabbitMQ and Celery are set up correctly and do not throw any errors.
Any ideas what I may have missed?
Thank you.

**Comment by chlarsen** [comment]
Thank you so much for that, I will check asap...
Much appreciated!

On December 11, 2018 9:29:05 AM UTC, Lincoln Simba <notifications@github.com> wrote:
>@Kirembu I have managed to replicate the issue. I believe this is what
>happens:
>
>![image](https://user-images.githubusercontent.com/12713110/49790544-87eca500-fd3f-11e8-89a0-21a53b7f7c8a.png)
>
>I managed to replicate this with one of redis or celery not running.
>But when I had them running, here's the result 
>
>![image](https://user-images.githubusercontent.com/12713110/49790659-d601a880-fd3f-11e8-8177-a01d233c0854.png)
>
>Please ensure `redis` is installed and running by using the command
>`redis-server` 
>Also ensure `celery` is instlled and running. You can use the command
>`celery -A onadata worker -l info` and have a look at the logs.
>
>This should help you with this issue.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/onaio/onadata/issues/1481#issuecomment-446132481

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lincmba** [comment]
@Kirembu Glad it's going on well so far. I haven't replicated the current issue you are facing but after a little searching I found [this](https://github.com/celery/celery/issues/4964) celery issue that is related. 
Try uninstalling pip `librabbitmq` if it's installed because it's the main culprit. Run `pip uninstall librabbitmq`.

**Comment by Kirembu** [comment]
@lincmba Thanks `pip uninstall librabbitmq` worked.

There are other apps that seemed to rely on that but I will deprecate them as per the link you've shared.

**Comment by Kirembu** [comment]
@lincmba Once again. `celery -A onadata worker -l info` Was quite handy..
I ran into the error below and was able to diagnose the issue as folder permissions:

> OSError: [Errno 13] Permission denied: '/srv/onadata/onadata/media/USERNAME/exports/MY_FORM'
...
...
> AttributeError: '_Frame' object has no attribute 'f_back'

Looks like everything with exports is working as expected for me now.

**Comment by lincmba** [comment]
Awesome. Thats great. 
You welcome.
