### ISSUE TITLE
Export with label choices not exporting data with labels for questions with choice filter

### ISSUE THREAD

**Issue by samwata** [onaio/onadata#1483]
When exporting data in Excel or CSV with label choices for questions with choice filter, the data does not export with labels.
For select one questions with choice filter the CSV and EXcel  exports does not export with labels  
For Select multiple questions with choice filter only excel formats that does not export with labels

**To Reproduce the issue**
Upload this [select one form](https://docs.google.com/spreadsheets/d/1pXLEE0-CNBhEqVnk6e2rIBTsOTwDyfl8bqdRpFDqlyQ/edit#gid=409613630) or [select multiple form](https://docs.google.com/spreadsheets/d/1BVr5hlmD1s6LZgITv-zk_DsRBZCshaEz9Rpda_M1DNo/edit#gid=1909949283)
submit some records and export CSV file or Excel file with labels

**Comment by faith-mutua** [comment]
@samwata I have been able to replicate this in only two instances; 
1. When filtering answer choices selected from a select_multiple question in a select_one question. Check this [form](https://ona.io/fkay/69435/355704).
2. When exporting data without splitting select multiple answer choices into separate columns. This only affects the filtered answers. See this [form](https://ona.io/fkay/69435/355745).

**Comment by lincmba** [comment]
This should be fixed by [this](https://github.com/XLSForm/pyxform/pull/235).

**Comment by faith-mutua** [comment]
@lincmba unfortunately, the two scenarios I had pointed out haven't been fixed yet. Could they be out of scope in regards to the fix?

**Comment by lincmba** [comment]
@faith-mutua This seems to work on staging running on `pyxform v0.12.2`. However production currently runs on `pyxform v0.11.5` which does not have the changes that fix this. 

@ukanga should this issue be closed?

**Comment by faith-mutua** [comment]
@lincmba great. Will you be deploying `pyxform v0.12.2` to production in the next release?

**Comment by lincmba** [comment]
Yes we will

**Comment by msschroeder** [comment]
@lincmba @faith-mutua I ams till encountering this error. Did we do the deployment as planned?
