### ISSUE TITLE
Add command to transfer projects in one user account to another user account

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1491]
Command: **transfer_user_projects**.

Transfer projects to a different user/organisation account.
- [x] Reassign created_by and organisation to the new owner/organisation.
- [x] Reassign all XForms under the user or project to the new
      user/organisation. Updating the fields `user` and `created_by`.
 - [x] Reassign all MergedXForms under the user or project to the new
      user/organisation. 
- [x] Reassign all Dataviews under the user or project to the new
      user/organisation. 
- [x] Apply project and form permissions to the new user.
- [x] Remove project and form permissions from the old user?
- [ ] Update Enketo references accordingly in issue #845 ?

**Comment by ukanga** [comment]
@msschroeder @ivermac 

- Anything I may have missed to add in this description relevant to transferring of entire projects from one user account to another?
- Does transferring the project also mean existing users with access to the project will no longer have access to the transferred project?
- Should this functionality also be exposed via API - for a user to transfer all their projects to another user?

**Comment by ivermac** [comment]
**_Anything I may have missed to add in this description relevant to transferring of entire projects from one user account to another?_**
> Looks good to me

**_Does transferring the project also mean existing users with access to the project will no longer have access to the transferred project?_**
> It makes sense to me to revoke any permission or access the existing users had to the project that has been transferred. I'd like to think it's up to the new user/org to share/re-share the project.

**_Should this functionality also be exposed via API - for a user to transfer all their projects to another user?_**
> If we ever need a UI for this functionality then i'd like to think exposing the functionality via the API would make sense
