### ISSUE TITLE
Add a 'NoRole' role 

### ISSUE THREAD

**Issue by Wambere** [onaio/onadata#1493]
When moving a project from one account to another, the new user should get all permissions to the project while the old user technically should have none. 
Currently the OwnerRole can be assigned to the new user to grant all permissions. But the best option for the old user is to assign the ReadOnlyRoleNoDownload role, in which the old user can still view the project.
Can we add a NoRole role?

**Comment by ukanga** [comment]
I would expect if a project is being transferred the original owner will retain permissions. A transfer of a project is more akin to moving a folder from one location to another place without changing who has access to the folder. I will consider changing the permission as a separate process which could be done by changing or removing a role from a user.

**Comment by Wambere** [comment]
In some cases for support issues a project is moved from a personal account to an organisation and the previous owner is not supposed to have any permissions.

I know of removing permissions, not role though. This would bring a situation where you remove all permissions and the user still has a role?

**Comment by DavisRayM** [comment]
Do we still need this within the project @ukanga @Wambere ?

**Comment by pld** [comment]
Closing this, let's double check this is documented, there's multiple ways to handle this, but the current way is fine for now.
