### ISSUE TITLE
Add a function and management command to delete User objects

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1502]
- [x] Add a function that aids in deleting `User` objects
- [x] Add a management comment that uses the above function to delete `User` objects, but before it does so it forces you to confirm that you really really are sure you want to delete that User account

#### Ideas on things that can be used to verify your strong intent to delete 
- name of one form
- name of one project
- username and email

**Comment by ukanga** [comment]
Anyone who wants to do this probably should be using the django admin. I don't see why this is relevant here.

**Comment by bmarika** [comment]
Related to https://github.com/onaio/onadata/issues/1566

**Comment by moshthepitt** [comment]
This is related and should be taken into account when implementing this: https://github.com/onaio/onadata/issues/1445
