### ISSUE TITLE
Create consistent Enketo URLs

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1503]
### Actual behaviour

When a form is transferred to a different user account, the Enketo URI changes. 

### Expected behaviour

Retain the same Enketo URI across different user accounts.

### Implementation plan

Setup a formList URI endpoint that is linked to only the form and not the user account. e.g /e/[UUID]/[formList|submission|etc]

**Comment by p-netm** [comment]
@ukanga 
I assume the use cases covered under **transferring to a different account** are as follows:
  - transferring a form to an organisation that the user is part of
  - transferring the a project to an organisation that the user is part of.
with help from @bkimondiu i have sufficiently replicated the described behaviour for the above 2 use cases, but i would also like to know if there is any other case that i may have overlooked?

**Comment by DavisRayM** [comment]
@kelvin-muchiri Are you still working on this ? Or is it free for anyone to pick up ?
