### ISSUE TITLE
Cannot upload XLS forms

### ISSUE THREAD

**Issue by chlarsen** [onaio/onadata#1504]
Greetings,
I have installed OnaData in a virtualenv inside a FreeBSD jail, running FreeBSD 10.4. Apart from the well-known py-amqp in versions > 2.3.0 (avoided by setting requirements to <2.3.0) and the inability to get UWSGi running (I am using gunicorn instead) there is a remaining pesky issue: I cannot upload XLS forms. The process fails after the actual form upload (recognised by increasing %) and the site issues a: "An error occurred while publishing the form. Please try again." This error occurs with and and without reverse proxy, with and without gunicorn, i.e. also when running manage runserver.
Any thoughts?
Thank you so much -
Chris
There is nothing in the logs. AMQ and RabbitMQ work fine.

**Comment by lincmba** [comment]
Hi @chlarsen 

I am trying to replicate your issue. How are you uploading the xlsform?

Meanwhile, follow [this](https://github.com/onaio/onadata/issues/1481) discussion, if it doesn't help get back.

**Comment by chlarsen** [comment]
Dear All,
I have in the meantime upgraded te entire system to FreeBSD 12, am still running the OnaData instance within a Python virtualenv inside a jail, and have upgraded to Python 3.6.
Still no luk with uploading forms, though. I get:
``````
Exception while resolving variable 'form_view' in template 'profile.html'.
Traceback (most recent call last):
  File "/usr/local/onadata/lib/python3.6/site-packages/django/template/base.py", line 882, in _resolve_lookup
    current = current[bit]
  File "/usr/local/onadata/lib/python3.6/site-packages/django/template/context.py", line 87, in __getitem__
    raise KeyError(key)
KeyError: 'form_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/onadata/lib/python3.6/site-packages/django/template/base.py", line 888, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'form_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/onadata/lib/python3.6/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'form_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/onadata/lib/python3.6/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
``````
The form_view-related error seems to be the mother of all problems here, and occurs both in debugging (manage.py runserver) and gunicorn mode.
What am I missing, as this is a real show stopper!
Thank you!
Chris

**Comment by DavisRayM** [comment]
@chlarsen Are you still encountering issues installing onadata ?

**Comment by DavisRayM** [comment]
Closing this, for now. Please reopen if this happens again.
