### ISSUE TITLE
Update authentication documentation to explain more clearly where and how one can obtain an access token 

### ISSUE THREAD

**Issue by WinnyTroy** [onaio/onadata#1507]

**Comment by moshthepitt** [comment]
Would also be cool to address this other issue while doing this one: https://github.com/onaio/onadata/issues/1469

**Comment by DavisRayM** [comment]
@WinnyTroy Mind providing more details ? Maybe a sample of the ideal structure for the document ?

**Comment by DavisRayM** [comment]
This doesn't seem to be relevant any more ? I'll be closing this for now. Please reopen if it's needed.
