### ISSUE TITLE
Unable to pull full org profile for org members with project manager role

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/onadata#1510]
Currently, organization members with `project manager` role don't have full access to the org profile when using the org profiles endpoint (`https://api.ona.io/api/v1/orgs/< org name >`). The `account-infor` key is returning a `null` value. This is a blocker on `zebra` since we require this map to check the `org plan type` before displaying certain paid features.

**Comment by JohnMwashuma** [comment]
Related to this [zebra](https://github.com/onaio/zebra/5503)  issue

**Comment by lincmba** [comment]
This issue belong to pricing and has therefore been created there and closed here . [Pricing issue link](https://github.com/onaio/pricing/issues/237)
