### ISSUE TITLE
Error in ODK Briefcase when pulling data in versions 11 to 13

### ISSUE THREAD

**Issue by bkimondiu** [onaio/onadata#1519]
The following error message is displayed in ODK Briefcase whenever versions 11 to 13 are used to pull data:

`Fetching form manifest
Error fetching form definition: Fetch of manifest failed. Detailed reason: Invalid url. Failed with error: no protocol: . Did you forget to prefix the address with 'http://' or 'https://' ?`

**Comment by lincmba** [comment]
After investigations, this is not an Onadata Issue but a Briefcase issue. The app fails without making a call to Onadata. It has been raised here [https://github.com/opendatakit/briefcase/issues/695](url) .

**Comment by ukanga** [comment]
@lincmba Reopenning this one, see https://github.com/opendatakit/briefcase/issues/695#issuecomment-452669581 for a way forward.
