### ISSUE TITLE
Unable to redirect to OAuth2 authorize page when signing in as another user from a client app/dashboard

### ISSUE THREAD

**Issue by KipSigei** [onaio/onadata#1531]
When trying to authorize a user to access a client dashboard or application with OAuth2 using the API as the OAuth provider, instead of redirecting to the OAuth2 auth page to allow the user to access the client app after successfully logging in to the API it redirects to the API homepage/landing page.

**Comment by moshthepitt** [comment]
@kahummer @KipSigei this might be easily fixed through https://github.com/onaio/onadata-template/issues/4

**Comment by ukanga** [comment]
This seems to only affect our production deployment, let's address this in https://github.com/onaio/onadata-template/issues/4 or related issue.
