### ISSUE TITLE
Limit number of images fetched when `/forms/{ form_id_string }/photos` is hit.

### ISSUE THREAD

**Issue by lincmba** [onaio/onadata#1560]
**Actual behaviour**

When this endpoint is hit `/username/forms/{ form_id_string }/ photos`,  links to as many photos as there are in all submissions to that form are fetched. 
This subsequently leads to as many calls to  `/attachments/small`. 

There needs to be a rearchitecting of how this is done. 

**Suggested implementations**

1.  Limit number of subsequent calls to `/attachment/small` to one at a time.
2. Paginate the response (limit to a given number say 10).
3. Do away with this feature in classic

**Comment by pld** [comment]
Is there a reason we need this endpoint? Why not simply remove it?

**Comment by lincmba** [comment]
@pld considering this being open source, maybe this is being used by others, in ways that we `Ona` don't.

**Comment by pld** [comment]
@lincmba true, how about a deprecation path then?

We can mark it as deprecated, wrap it in a feature-flag that is disabled by default, and deployments can set that feature-flag to true in settings if they need to re-enable

**Comment by ukanga** [comment]
If this goes on depreciation path then the entire classic interface should go on a depreciation path and only leave behind the `/api` functionality.

My vote will be on pagination but as something that we are facing out or rather no longer willing to develop any further, the pagination should be supported with URL changes and not by making any UI changes. Limit should be more sensible like between 50 and 100 I think.

**Comment by pld** [comment]
Agree, we had a note on this, but never got around to it, https://github.com/onaio/onadata/issues/787

**Comment by lincmba** [comment]
Technically, here's what happens when the page is hit:
1. All submissions are fetched.
2. All attachments in each submission is fetched
3. Image urls are generated and added to a list
4. The template `form_photos` is then rendered with this list. 

Step 4 is what causes us problems because of this code `{% for image_url in images %}` that loads all images in the list, hitting `attachment/small` as many times.

**Comment by ukanga** [comment]
That will be ideal, we need to be careful though that we do not dump 20k strings in memory on the server side. Though this will be acceptable for an endpoint we are considering this endpoint as being deprecated.
