### ISSUE TITLE
Get monthly submissions for an entire year from the user Profiles Endpoint.

### ISSUE THREAD

**Issue by WinnyTroy** [onaio/onadata#1569]
### Environment (local, stage, preview, production)
All

The current implementation returns a user's monthly submissions, i.e the count of private and public submissions of the month and year specified. If the month and year are not specified, it returns the monthly submissions for the current month.

https://api.ona.io/static/docs/profiles.html#get-the-total-number-of-monthly-submissions

The proposed implementation would return monthly submissions for the same user, for a time span of 12 months(1 year).

**Comment by lincmba** [comment]
I suggest redesigning the endpoint `/profiles/ {username} /monthly_submissions`, or building another that's dynamic enough to allow custom date filtering. i.e `/profiles/ {username} /submissions`  to allow `/profiles/ {username} /submissions?submission_date__gt={ date }&submission_date__lt={ date }`

**Comment by DavisRayM** [comment]
CC: @ivermac @ukanga

**Comment by DavisRayM** [comment]
This doesn't seem to be relevant any more ? I'll be closing this for now. Please reopen if it's needed.
