### ISSUE TITLE
Add metadata function for submission review data_type

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#1585]
Ideally, it would be more less same as the following but now for submission review
https://github.com/onaio/onadata/blob/7941f714633b858fdec9af26014f9e3091b519bf/onadata/apps/main/models/meta_data.py#L254-L257
The data_value should either be `True` or `False`

**Comment by ukanga** [comment]
We might need to also look at the `/metadata` endpoint to ensure we only create one only single `submission-review` metadata for a form. 
```python
data_type = 'submission-review'
data_value = 'true'
```
