### ISSUE TITLE
Clear error message for form upload failure

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#1590]
### Environment (local, stage, preview, production)

All

### Expected behavior

The error message returned when uploading a form that has spaces in the filename from Dropbox should clearly state that the form title/filename should not contain spaces. 

### Actual behavior

Currently, the error message returned when uploading a form that has spaces in the title/filename from Dropbox is not very clear. The server adds a prefix to the form title/filename and some other characters in between which makes the form title/filename an invalid XML tag. See below screenshot

### Steps to reproduce the behavior

- Upload a form that has spaces in the title/filename from Dropbox.

**Comment by lincmba** [comment]
This has been addressed in PyXform and should be fixed by [this](https://github.com/XLSForm/pyxform/pull/280)

**Comment by ivermac** [comment]
Closed by pyxform fix
