### ISSUE TITLE
Activate webform link when meta permissions are set to dataentry-only

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#1600]
**Environment**

All

**Expected behavior**

Users with **Can Submit** permission should be able to submit data via Enketo even when the permission restriction for the **Can Submit** role is set to **Block access to all data**.

**Actual behavior**

Users with Can Submit (data entry) permission are unable to launch webforms when the permission restriction under the Can Submit role is set to **Block access to all data**. Clicking on a webform loads a 404 error page. 

**Steps to reproduce**
- Add a user to a project and assign Can Submit role.
- In one of the forms, under settings, set the permission restriction for Can Submit role to **Block access to all data**
- Log into the account that belongs to the user with the Can Submit role and click on a webform link.

**Comment by lincmba** [comment]
This issue was addressed by #1602 . @faith-mutua please test to confirm this was fixed.

**Comment by faith-mutua** [comment]
@lincmba the issue has been resolved. Closing this issue
