### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 36: invalid start byte

### ISSUE THREAD

**Issue by lincmba** [onaio/onadata#1628]
https://sentry.onalabs.org/ona/onadata/issues/70142/

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 36: invalid start byte
  File "onadata/libs/utils/csv_import.py", line 256, in submit_csv
    for row in csv_reader:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 36: invalid start byte
```

**Comment by WinnyTroy** [comment]
I believe this happened as expected. The function reports this error when it receives non-ASCII input, it's however caught in a try-except block.

**Comment by WinnyTroy** [comment]
Closing this as it is now being fixed by validating appropriately in the csv import functionality.
Kindly re-open this when/if it arises again
