### ISSUE TITLE
Track users who delete submissions

### ISSUE THREAD

**Issue by lincmba** [onaio/onadata#1640]
When submissions are deleted, both the timestamp and user who deleted it should be tracked.
Currently, only the timestamp is logged and not the users who did the deletion.

**Comment by shreyanshrs44** [comment]
Hi, I would like to work on this issue . Also this is my first attempt contributing to onadata. Can you tell me from where I should start working on this issue ?

**Comment by lincmba** [comment]
Hi @shreyanshrs44. Glad to hear that. I will give a few pointers.

First, look at the Instance model, onadata/apps/logger/models/instance.py and how we track the timestamp and user upon deletion.

Then have a look at the view performing the deletion onadata/apps/api/viewsets/data_viewset.py and what's missing.

Don't forget a test.

**Comment by shreyanshrs44** [comment]
Thanks for your help. I am working on this issue and trying my best to solve it.
