### ISSUE TITLE
Flow data results in a merged dataset is blank

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1643]
The flow data results endpoint returns blank for a merged dataset form- https://api.ona.io/api/v1/flow-results/packages/{UUID}/responses whereas the data endpoint - https://api.ona.io/api/v1/data/{pk}.json - would return data.

There should be data returned from the flow data results endpoint.

**Comment by DavisRayM** [comment]
Merged Datasets / [`MergedXForms`](https://github.com/onaio/onadata/blob/master/onadata/apps/logger/models/merged_xform.py) currently do not have a `UUID`. In these case we might need to add the field in order to not go against the [FLOIP Spec](https://floip.gitbooks.io/flow-results-specification/content/specification.html#geo_point).

I fell like the migration necessary for this would break backwards compatibility.

**Comment by pld** [comment]
Why would it break backwards compatability?

**Comment by DavisRayM** [comment]
> Why would it break backwards compatibility?

Pre-existing Merged Datasets won't have the field and I feel like the `UUID` field should not be null. I think that would cause a lot of issues.

**Comment by DavisRayM** [comment]
The other approach would be to allow null values on the field. But I'm not so sure how to go about update and adding uuid's for Merged Datasets created before this change is implemented.

**Comment by pld** [comment]
> > Why would it break backwards compatibility?
> 
> Pre-existing Merged Datasets won't have the field and I feel like the `UUID` field should not allow null values. I think that would cause a lot of issues.

Can we use a data migration to fill this field? An require that it not be null

**Comment by DavisRayM** [comment]
> > > Why would it break backwards compatibility?
> > 
> > 
> > Pre-existing Merged Datasets won't have the field and I feel like the `UUID` field should not allow null values. I think that would cause a lot of issues.
> 
> Can we use a data migration to fill this field? An require that it not be null

Confirmed with @ivermac seems like setting a default would fill this field with a default. And from this post [here](https://stackoverflow.com/questions/34264391/how-can-auto-create-uuid-column-with-django), seems like its possible to set a uuid as default.

**Comment by DavisRayM** [comment]
Researched a bit into the FLOIP spec as suggested [here](https://github.com/onaio/onadata/pull/1773#pullrequestreview-406818284). Noted down the following:

<img width="1280" alt="Screenshot 2020-05-07 at 09 59 36" src="https://user-images.githubusercontent.com/25849009/81265210-5d456f80-904b-11ea-9b3e-eb3f3c5e7c0a.png">

The FLOIP spec supports the following Question types: multiple_choice_one/select_one, multiple_choice_many/select_many, numeric, open, text, image, video, audio, geo_point, date, time, datetime

_The `multiple_choice_many` and `multiple_choice_one` seem to have been replaced with `select_one` and `select_many`... The spec lists multiple_choice_* [here](https://floip.gitbook.io/flow-results-specification/specification#resource), but [here](https://floip.gitbook.io/flow-results-specification/specification#question-types) it's `select_one` and `select_many`_

<img width="1280" alt="Screenshot 2020-05-07 at 09 53 48" src="https://user-images.githubusercontent.com/25849009/81265676-2c196f00-904c-11ea-8247-9bbbda470170.png">

The 'name' metadata should be on the same level as 'title' according to [this](https://floip.gitbook.io/flow-results-specification/specification#descriptor) and [this](https://floip.gitbook.io/flow-results-specification/api-specification#get-the-descriptor-of-a-package)

The other change already identified in the conversation on #1773 is that the 'id' returned should be a completed UUID4 (hex+digits) this would possibly require us to change how we set uuid's for all the XForms on onadata....

**Comment by ukanga** [comment]
> The other change already identified in the conversation on #1773 is that the 'id' returned should be UUID4 (hex+digits) this would possibly require us to change how we set uuid's on onadata..

I think we do not necessarily need to change that but we could. From how we store it you can get the dashed version:
```python
>>> import uuid
>>> uuid.UUID('a94dc0c6f4bb4cea95af8df3969c67bc')
UUID('a94dc0c6-f4bb-4cea-95af-8df3969c67bc')
>>>
```

**Comment by ukanga** [comment]
Please create issues for the others so that we can make the changes to conform to specification.

**Comment by DavisRayM** [comment]
> Please create issues for the others so that we can make the changes to conform to specification.

Created an issue for the others, [here](https://github.com/onaio/onadata/issues/1826)
