### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1655]
https://sentry.onalabs.org/ona/onadata/issues/70151/

```python

AttributeError: 'str' object has no attribute 'items'
  File "onadata/libs/utils/csv_import.py", line 319, in submit_csv
    row = csv_dict_to_nested_dict(row)
  File "onadata/libs/utils/dict_tools.py", line 120, in csv_dict_to_nested_dict
    merged_dict = merge_list_of_dicts(results)
  File "onadata/libs/utils/dict_tools.py", line 66, in merge_list_of_dicts
    result[k] = merge_list_of_dicts([result[k], v])
  File "onadata/libs/utils/dict_tools.py", line 66, in merge_list_of_dicts
    result[k] = merge_list_of_dicts([result[k], v])
  File "onadata/libs/utils/dict_tools.py", line 59, in merge_list_of_dicts
    for k, v in row.items():

AttributeError: 'str' object has no attribute 'items'
```

```python
list_of_dicts = ['de1 de2 de6', {'de1': 'True'}]
row = 'de1 de2 de6'
```

**Comment by DavisRayM** [comment]
In this scenario what should we do to the extra field added on top `{'de1': True}` ? Previously the accepted approach was to delete the extra field but I wonder if this may lead to the deletion of some important data in some cases.

CC: @ukanga @WinnyTroy @ivermac

**Comment by WinnyTroy** [comment]
@DavisRayM Trying to replicate this error currently fails.
I have tried importing data using csv where I include a populated column and an empty column, adhering to the select multiple naming conventions of that question.
That was how we were able to initally replicate this problem. Sample csv file is here

**Comment by WinnyTroy** [comment]
@DavisRayM This error is very specific to one scenario.
It only occurs when a select_multiple question is in a group/repeat group and a use tries to add an extra column adhering to the group/qstn_name convention. e.g
![repeat_group_extra_column](https://user-images.githubusercontent.com/11174326/76511245-f7ca6d80-6463-11ea-9402-4342041073ab.png)

With that specified, I believe that we can remove this extra column from the row when uploading using csv without the worry of deleting important information.

Using this .xlsx file to demonstate [groupxlsreport_1.xlsx](https://github.com/onaio/onadata/files/4323534/groupxlsreport_1.xlsx) that select multiple questions not within a group are able to resolve any extra field introduced without throwing an error. 

Adding this populated column 
![no_group_extra_column_data](https://user-images.githubusercontent.com/11174326/76510488-c43b1380-6462-11ea-8463-350703d1428d.png) the data is resolved successfully as seen here 
![extra_column_success](https://user-images.githubusercontent.com/11174326/76510536-d6b54d00-6462-11ea-8926-7fdea2529e2d.png) 

However, irregardless of the option you choose when importing this data using csv i.e `Add new or edit existing questions` or `Overwrite or replace all records` , the values returned by the api for these select multiple questions are null.
![extra_column_no_group_table](https://user-images.githubusercontent.com/11174326/76511052-9c987b00-6463-11ea-891c-d25a9b8a492b.png)

This behavior is consistent for both of these scenarios we are describing here, when you import data for the select_multiple question in a group or not in a group.
This also reminds me of [this](https://github.com/onaio/zebra/issues/5635#issuecomment-593289135) current issue for the select multple qstn. 
![extra_column_table_view](https://user-images.githubusercontent.com/11174326/76511083-aa4e0080-6463-11ea-8ba7-99c346691e33.png)

This issue however, emphasizes the need to priorotise discussion on this [issue](https://github.com/onaio/onadata/issues/1795) that @ukanga raised.
