### ISSUE TITLE
Preventing a private form not to be in a public project or public form not be in a private project

### ISSUE THREAD

**Issue by samwata** [onaio/onadata#1660]
There have been many cases where when a user moves a form from private project to public, due to server error, the form does not change the permissions from private to public.
This causes a private form to be in a public project.
When this scenario happens the user get this error when they try to export data from this form.
![image](https://user-images.githubusercontent.com/23456184/61620825-4a0f1200-ac7a-11e9-979c-76b803947657.png)

Since these cases have increased lately, How can we prevent private form not be in public project or vice versa?
Is there a way we can catch this error while moving the form and prevent the form to be moved and give an error message like `Form move failed please try again`?

**Comment by DavisRayM** [comment]
There currently is a piece of code meant to handle these situations which updates the XForm / Forms public status according to the project it's in. This code is supposed to run after the XForm/Form has been moved.

The cause of this may be due to the signal either not firing or not running immediately after the form is moved. _The code responsible for this is [here](https://github.com/onaio/onadata/blob/fdd91d7024c9b15ee1eee4e074e2e0ef21939b8b/onadata/libs/utils/project_utils.py#L26)_

An option would be to move that line of code directly into the same location where the code for moving an XForm is present.

CC: @ukanga @ivermac

**Comment by ivermac** [comment]
@DavisRayM could you please add here what we discussed about `AppConfig.ready`?

**Comment by DavisRayM** [comment]
> @DavisRayM could you please add here what we discussed about `AppConfig.ready`?

Yep, another option to cross out the signals not being registered at some points would be registering all the signals within the [`AppConfig.ready()`](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig.ready). This may help alleviate the issue of the signals not firing at all in some weird cases.

We've done the above for the messaging app too. [`MessagingConfig`](https://github.com/onaio/onadata/blob/fdd91d7024c9b15ee1eee4e074e2e0ef21939b8b/onadata/apps/messaging/apps.py#L10)

**Comment by DavisRayM** [comment]
Dived into the code a bit and noticed that we only switch an XForms' status to the projects status if it's not public before the transfer. _Specific [code block](https://github.com/onaio/onadata/blob/920f624acf8130bf70b84dab36c56b00485b03a4/onadata/libs/utils/project_utils.py#L23-L26)_. Is this how it's supposed to be ? I'm not entirely sure why this should be this way....

CC: @ukanga @denniswambua

**Comment by ukanga** [comment]
Before projects were implemented, we could turn forms public or private, the same could be applied to the form data separately. You can see this in this functionality in the classic UI that is part of this repository when you got to domain.tld/forms. This classic UI has no concept of projects other than via the API hence the reason we still support this functionality. Hence, you may have public forms in private projects. We may perhaps need to expose this in the Zebra UI. 
As for the code check, https://github.com/onaio/onadata/blob/920f624acf8130bf70b84dab36c56b00485b03a4/onadata/libs/utils/project_utils.py#L23-L26, we could remove the check and blindly apply the project.shared value.
