### ISSUE TITLE
Signatures and drawings not saved in S3

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#1685]
**Environment**

Production

**Expected behavior**

Signatures and drawings should be viewable in fullscreen view in zebra and in downloads. 

**Actual behavior**

Clicking on the signature/drawing links loads a blank page. Downloading a zipped folder of media files downloads blank files for signatures/drawings.

**Steps to reproduce**
- Upload this [form](https://docs.google.com/spreadsheets/d/17O98r1626B1IsxEPe5LS6bdB1svVktxvD9QR2Ep1Ugs/edit?usp=sharing) to your project. 
- Make a few submissions
- Click on a signature/drawing to view it in fullscreen. 
- Download the zipped folder of media files.

**Comment by RayceeM** [comment]
Reference Zebra issue onaio/zebra#5721
