### ISSUE TITLE
MQTT messages are not sent

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1702]
MQTT messages in rare cases are not sent to the MQTT backend even though an `Action / Message` is created and is accessible from the `api/v1/messaging?target_type=<target>&target_id=<id>` endpoint.

Suspected issue: [This](https://github.com/onaio/onadata/blob/master/onadata/apps/messaging/backends/base.py#L19) line could be executed in the case that the replica / read server does not have the object and thus the process silently fails.

**Comment by DavisRayM** [comment]
@ivermac Suggested passing the `Instance` / `Action` object directly instead of passing the `instance_id` [here](https://github.com/onaio/onadata/blob/master/onadata/apps/messaging/signals.py#L30) in order to cross out the desync between the replica database and master database. @ukanga @moshthepitt Will this change break anything else ? Or should i go forward with applying this solution ?

**Comment by moshthepitt** [comment]
@DavisRayM I think it is (or used to be) discouraged - and sometimes you get weird serialization issues - to pass objects to celery tasks, so I am not sure if that will work well.

**Comment by DavisRayM** [comment]
@moshthepitt I'm guessing it was due to the fact that we used celery's [default serializer(JSON)](https://docs.celeryproject.org/projects/kombu/en/stable/userguide/serialization.html) we could set another serializer like `pickle` for this particular task in order to ensure that the instance object is correctly serialized ?

**Comment by ukanga** [comment]
I would go with using the `@use_master` decorator.

```python
@use_master
def call_backend(backend, instance_id, backend_options=None):
```

**Comment by DavisRayM** [comment]
@ukanga I think going with the `@use_master` decorator is perfect in this case, i'll make a PR with that change.
