### ISSUE TITLE
Create API endpoint for obtaining the most recent form version set on an xform.

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#1721]
Following the discussion here: https://github.com/onaio/kaznet-web/issues/346 an API endpoint needs to be created that returns the most recent version of a form that has been set on an xform.

**Comment by FrankApiyo** [comment]
I plan to use this https://docs.python.org/3/library/xml.etree.elementtree.html to get the value of the version field within  an `@property` field in the `XForm` model.  and then just create an endpoint that returns the value of this field for a single `XForm`

**Comment by ukanga** [comment]
You might not need to read through the XForm XML. You could use the XForm JSON stored in the `XForm` model object under the `json` property. It is of the form: It is the exact value that would be on the XForm XML.

```JSON
{
  "default_language": "default",
  "id_string": "tutorial",
  "children": [
    {
      "name": "name",
      "label": "Where?",
      "type": "text"
    },
    {
      "name": "age",
      "label": "How many People Present?",
      "type": "integer"
    },
    {
      "name": "picture",
      "label": "Photo?",
      "type": "photo"
    },
    {
      "name": "gps",
      "hint": "GPS coordinates can only be collected when outside.",
      "label": "your GPS coordinates.",
      "type": "geopoint"
    },
    {
      "control": {
        "bodyless": true
      },
      "children": [
        {
          "name": "instanceID",
          "bind": {
            "readonly": "true()",
            "calculate": "concat('uuid:', uuid())"
          },
          "type": "calculate"
        }
      ],
      "name": "meta",
      "type": "group"
    }
  ],
  "version": "201903010714",
  "type": "survey",
  "name": "tutorial",
  "sms_keyword": "tutorial",
  "title": "tutorial"
} 
```

You will need to get the top-level `version` property value from this file.

I suppose you can access the version from the API endpoint `/api/v1/forms/[pk]/form.json`.

**Comment by FrankApiyo** [comment]
huh... seems there's not need to create a new endpoint anymore.
