### ISSUE TITLE
Return XForm versions even if the version is not a number

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1726]
We are currently not returning XForm versions if the version is not a digit. Which ends up breaking exports through ODK Briefcase for KPI built forms.

**Comment by DavisRayM** [comment]
This issue clashes with #982

**Comment by ggalmazor** [comment]
Thanks for documenting this issue, @DavisRayM.

Indeed, we've seen interoperability issues with Aggregate servers when versions don't follow the 10 digit pattern. Briefcase doesn't parse version strings so far, so having alphanumeric versions shouldn't be an issue.
