### ISSUE TITLE
Set default submission review status when enabled

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#1743]
It would be nice if the `data` endpoint would return submission review status and submission review comments by default when the submission review feature has been enabled for a specific form. A suggestion would be to have the following when submission review has been enabled and the instance has no submission review because `3` is the code for `Pending` status:
```json
...
_review_comment: ""
_review_status: "3"
...
```
This will also make it easier to filter data by submission review status especially when the data doesn't have a submission review. For example would work well:
```json
"/api/v1/data?start=0&limit=100&query={"_review_status":"1"}"
```

**Comment by DavisRayM** [comment]
This may be quite painful to do for forms that already have preexisting instances. When the feature is enabled we would have to update all the `.json` values for the Instances as that's what is rendered and filtered on this endpoint.

**Comment by DavisRayM** [comment]
@ivermac I think you're suggestion of just adding a `not equal to` filter on the endpoint would be good enough for the front end to distinguish what is `Pending`, I'll add that feature within the already opened PR #1749 .

**Comment by DavisRayM** [comment]
Any opinions on this approach @ukanga ?

**Comment by ukanga** [comment]
Perhaps we need to use constants, `pending`, `reviewed` and perhaps a top-level filter `/api/v1/data/[form pk].json?review=pending` which would translate to a `_review_status=3 or _review_status is null` query against the DB. 

Currently, the way to achieve that is doing the same query for pending would be to use the construct:
```
/api/v1/data?start=0&limit=100&query={"$or": [{"_review_status":"1"}, {"_review_status": null}]}
```

Perhaps we may need to add a special case to handle when the field does not exist. Hence, maybe, having a `review` filter might give us that flexibility or an extension of the functionality in https://github.com/onaio/onadata/blob/e4fe81c0eb0387212a33ac263d64f748885418a1/onadata/apps/viewer/parsed_instance_tools.py#L104.

**Comment by WNjihia** [comment]
@DavisRayM I'm currently waiting for the [fix for enabling submission reviews](https://github.com/onaio/zebra/issues/5813) so I can be able to test this

**Comment by ivermac** [comment]
@WNjihia Let's go ahead and test this using a tool like postman, curl or httpie. We need to make a request to the metadata endpoint to create the submission review then query the data endpoint using the query params mentioned in this PR
