### ISSUE TITLE
A cookie associated with a cross-site resource at http://dropbox.com/ was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1744]
The warning below is displayed in chrome when accessing the default API site:

> A cookie associated with a cross-site resource at http://dropbox.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by DavisRayM** [comment]
Haven't been able to replicate this. Let's re-open the issue if it occurs again.
