### ISSUE TITLE
Found 2 elements with non-unique id #id_xls_file

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1745]
[DOM] Found 2 elements with non-unique id #id_xls_file: <input type=​"file" name=​"xls_file" id=​"id_xls_file">​ <input type=​"file" name=​"xls_file" id=​"id_xls_file">​

**Comment by ivermac** [comment]
@ukanga could you please add more details to this issue

**Comment by DavisRayM** [comment]
Going to close this due to a lack of information. Kindly re-open if this ever happens again.
