### ISSUE TITLE
ODK Briefcase v1.17+ Support

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1763]
### Environmental Information

- Operating System: Mojave, Ubuntu 18.04
- Onadata version: v2.1.2
- Python version: Python3.6
- ODK Briefcase version: v1.17.1

### Problem description

Some of the ODK Aggregate endpoints built to support ODK Briefcase are not working well with the latest versions of ODK Briefcase. One endpoints I noticed was `formUpload` / `upload` endpoint which return a 401 on the first `POST` request sent by ODK Briefcase v1.17.1.

### Expected behavior

Either ODK Briefcase should be able to a 401 when trying to `POST` data or we re-work our Digest Authentication flow.

### Steps to reproduce the behavior

1. Create an `Organization` or `User`
2. Try to push a form to `<onadata_url>/<user>`
3. Should get a 401 in the ODK Briefcase logs

### Additional Information

ODK Briefcase v1.17.1 flow[Fails to push data]:
<img width="350" alt="Screenshot 2020-01-10 at 11 15 37" src="https://user-images.githubusercontent.com/25849009/72136762-9110d100-339a-11ea-9c12-e7349643adaf.png">

ODK Briefcase log:
[briefcase.log](https://github.com/onaio/onadata/files/4044533/briefcase.log)

**Comment by DavisRayM** [comment]
Related to opendatakit/briefcase [issue #801](https://github.com/opendatakit/briefcase/issues/801). This should have been fixed by the latest release v1.17.2, I'll investigate it further to make sure.

**Comment by bkimondiu** [comment]
@DavisRayM Please find attached my Briefcase log:

[briefcase.log](https://github.com/onaio/onadata/files/4097775/briefcase.log)

**Comment by DavisRayM** [comment]
> Related to opendatakit/briefcase [issue #801](https://github.com/opendatakit/briefcase/issues/801). This should have been fixed by the latest release v1.17.2, I'll investigate it further to make sure.

As far as I can tell ODK Briefcase is failing due to `cannot retry request with a non-repeatable request entity`. No auth credentials are passed on the first POST request as such I assume they are trying to initiate the Digest flow and getting exceptions on their side.

![ODK Briefcase](https://user-images.githubusercontent.com/25849009/72973177-d7742000-3ddd-11ea-948e-4bf28754e088.png)

CC: @ukanga @lincmba @jasonrogena

**Comment by DavisRayM** [comment]
Opened an issue on briefcase about this, follow along with the conversation [here](https://github.com/opendatakit/briefcase/issues/852).

**Comment by DavisRayM** [comment]
It's been noted while testing the authentication fix on Briefcase that the latest version of onadata(master) is facing issues.

https://github.com/opendatakit/briefcase/pull/856#issuecomment-598727025

I'll be investigating this and increasing the priority of this issue.
