### ISSUE TITLE
Login page does not show form validation errors

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata#1768]
### Environmental Information

- Onadata version: `v2.1.2 (2020-01-09)`
- Python version: `all`

### Problem description

This page https://api.ona.io/accounts/login/ does not render form validation errors. e.g. when password is wrong, account is inactive etx

### Expected behavior

Form validation messages should be shown.

### Steps to reproduce the behavior

Try and log in as an inactive user.  You wont get any indication of what went wrong.

**Comment by DavisRayM** [comment]
Related to #1742

**Comment by lincmba** [comment]
This should have been fixed by this https://github.com/onaio/onadata-template/pull/6, I believe. Unless it's still a problem.

**Comment by ivermac** [comment]
Seems to have been fixed
![Screenshot 2020-06-29 at 08 23 06](https://user-images.githubusercontent.com/1128227/85975834-cdd09300-b9e1-11ea-9a82-f23ce5f3e366.png)
I'm going to close this issue
