### ISSUE TITLE
Upgrade Django version

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1769]
### Environmental Information

- Operating System: All
- Onadata version: Master
- Python version: All

### Problem description

Onadata is currently running on Django 2.1 which is no longer being supported as far as I know. In order to keep up to date with all the security and maintenance patches we should update our version of Django to the latest LTS version

### Expected behavior

- N/A

### Steps to reproduce the behavior

- N/A

### Additional Information

- N/A

**Comment by DavisRayM** [comment]
The current options we have is version 2.2 LTS or the latest version of Django (3.0).

More Info (Under _Supported Versions_ header) [here](https://www.djangoproject.com/download/).

**Comment by moshthepitt** [comment]
2.2 is a gentler and easier target to fix the immediate problem (which is using an unsupported version)

**Comment by ivermac** [comment]
I'd say we go for 2.2 as well because it has long term support
