### ISSUE TITLE
Investigate requirement upgrades required for the Django 2.2 upgrade

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1787]
### Environmental Information

- Onadata version: v2.2.1

### Problem description

The current onadata installation has packages that _may_ be incompatible with Django v2.2.1 . The incompatibility may not be immediately noticeable `500` status codes or the link but may bring down functionality that we usually expect to work out of the box i.e Async functionality.

~One of the packages currently not compatible with Django v2.2.9 is [celery 4.2.1](https://github.com/onaio/onadata/blob/master/requirements/base.pip#L20) and possibly [raven](https://docs.sentry.io/clients/python/integrations/#django).~

It seems the incompatibility/failure is being caused by [PyXForm](https://github.com/XLSForm/pyxform/issues/401). This issue is fixed in their latest release.

_Celery may be the only package that is currently incompatible with Django v2.2.9. But, it won't hurt to thoroughly investigate further_

**Comment by DavisRayM** [comment]
Seems like `raven` is now the legacy client for Sentry logging. Might be a good move to upgrade to the latest client `sentry-python`. Not sure if this move should happen in alongside the celery upgrade(possibly other requirement upgrades).

Also not sure if we have a preferred way of going about requirement upgrades ? Should one usually upgrade all the packages together `pip-compile --upgrade -o <requirements.pip> <requirements.in` / `pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U` or a more controlled approach where we update individual packages ?

CC: @ivermac @WinnyTroy @lincmba @ukanga

**Comment by ukanga** [comment]
I prefer the `pip-compile` options as well as being controlled or deliberate on major components like Django, Celery, Pyxform, Django RestFramework.

**Comment by ukanga** [comment]
Any upgrade of major packages specifically Django and Django RestFramework should include an overhaul of all dependencies.

**Comment by DavisRayM** [comment]
> Any upgrade of major packages specifically Django and Django RestFramework should include an overhaul of all dependencies.

All dependencies tied to the major package i.e `Django` or `onadata` ?

**Comment by ukanga** [comment]
> All dependencies tied to the major package i.e `Django` or `onadata` ?

I meant Django.

**Comment by DavisRayM** [comment]
> > All dependencies tied to the major package i.e `Django` or `onadata` ?
> 
> I meant Django.

Ahh I see. Any advice on how one should handle "odd cases" such as `Celery` which isn't really a dependency of `Django` but does interact with it in a sense and could cause weird incompatibility issues ?

**Comment by lincmba** [comment]
> Ahh I see. Any advice on how one should handle "odd cases" such as Celery which isn't really a direct dependency of Django but does interact with it in a sense and could cause weird incompatibility issues ?

I guess this is the case where we control it, fix it to a specific version

**Comment by ukanga** [comment]
With pip-tools, perhaps what I forgot to do when reviewing the PR and testing this out yesterday is using the `--upgrade` option which factors in upgrades.
```bash
pip-compile --upgrade -o requirements/base.pip requirements/base.in
```

When you delete the pip files then pip-comp

**Comment by DavisRayM** [comment]
> With pip-tools, perhaps what I forgot to do when reviewing the PR and testing this out yesterday is using the `--upgrade` option which factors in upgrades.
> 
> ```shell
> pip-compile --upgrade -o requirements/base.pip requirements/base.in
> ```

I did try this command but it did bring in a few changes that we may need to slowly upgrade to; one being the fact that `rest_framework` has had a few changes. I believe some filters we currently use are not available on the latest release. Though, I wasn't really keen into looking into the other upgrades...

**Comment by ukanga** [comment]
When upgrading Django previously we looked at the changelogs for celery and restframework. We learned what changes were applied and identified which changes we would have to make on the entire codebase. And implemented those changes before we would merge the codebase. 
I think it should just be part of the update process, perhaps we need to document or add the upgrade checklist.

**Comment by DavisRayM** [comment]
> When upgrading Django previously we looked at the changelogs for celery and restframework. We learned what changes were applied and identified which changes we would have to make on the entire codebase. And implemented those changes before we would merge the codebase.
> I think it should just be part of the update process, perhaps we need to document or add the upgrade checklist.

I think having an upgrade checklist would be amazing. I'll create an issue to add it a checklist of sorts when it comes to package upgrades.... maybe a section in the [contributing](https://github.com/onaio/onadata/blob/master/CONTRIBUTING.MD) guidelines ?

**Comment by ukanga** [comment]
> I did try this command but it did bring in a few changes that we may need to slowly upgrade to; one being the fact that `rest_framework` has had a few changes. I believe some filters we currently use are not available on the latest release. Though, I wasn't really keen into looking into the other upgrades...

Applying all those changes is what it takes. But sometimes you can choose to pin specific versions as long as the compatibilty of versions works. It is testing.
