### ISSUE TITLE
Bug on ODK Briefcase 

### ISSUE THREAD

**Issue by akahure** [onaio/onadata#1790]
### Environmental Information
- Operating System:
- Onadata version:
- Python version:

### Problem description
The export file from Step 3 does contain the first set of forms submitted, but the export file from Step 6 does not contain any new forms.
### Expected behavior
The export file from Step 3 should contain the first set of forms submitted, and the export file from Step 6 should contain just the additional forms submitted in Step 4.
### Steps to reproduce the behavior

1. Submit some (encrypted) forms from Android device to Aggregate server
2. Run ODK Briefcase CLI command --pull_aggregate to import the files to an empty storage directory
3. Run ODK Briefcase CLI command --export with the --smart_append option to export the files to an empty export directory, and specifying an export file
4. Submit some more (encrypted) forms from Android device to Aggregate server
5. Run ODK Briefcase CLI command --pull_aggregate to import the files same storage directory as in Step 2
6. Run ODK Briefcase CLI command --export with the --smart_append option to export the new files to the the same export directory as in Step 3, specifying a different export file from Step 3.

### Additional Information (from client)
On inspection of ODK Briefcase code, it appears that when the Briefcase attempts to parse the submission.xml file to obtain the submissionDate (see SubmissionParser.java - readSubmissionDate -> parseAttribute). The following exception is being thrown:  

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,266]
Message: Attribute "xmlns" was already specified for element "n0:data".

`<n0:data encrypted="yes" id="RD_Test_SARC" instanceID="uuid:c32bcf14-fd59-4774-a857-50f471dd6a5b"
         submissionDate="2020-02-13T16:00:03.983518+00:00" version="202002131555"
         xmlns="http://www.opendatakit.org/xforms/encrypted" xmlns="http://opendatakit.org/submissions"
         xmlns:n0="http://www.opendatakit.org/xforms/encrypted">
    <n0:base64EncryptedKey>
        FXbiLo4+u0SFpp0KsgF81n7YT1sFOTV8dewoBHiiIezkbJffJvVQhWF/0FmJLRDWTKRNB85JlIIjva3HYB+1V6mefHPKKX1ZdCXbFdc7GJHnVmYNO9atdW/1/tZvtjagnB50NyvifWeY3689BUrP5JFxah5hFbKqeGWI8gUCHAtC7Ay3El49SadmdnlJQ+codaa1nPL7fW+uW/K8FZ+P9dA238qhwb0Hb505HKZsjC37cftXTD0oQbUtIhqdUwqIAUSMjMx+BBYHe9a/rCoAIMQ3R5xt0W5cQWnaJI/RnUreH59WQTYknk5wCR0ULNMjywAhKZXAIFj5i2uVUdNJUw==
    </n0:base64EncryptedKey>
    <orx:meta xmlns:orx="http://openrosa.org/xforms">
        <orx:instanceID>uuid:c32bcf14-fd59-4774-a857-50f471dd6a5b</orx:instanceID>
    </orx:meta>
    <n0:encryptedXmlFile>submission.xml.enc</n0:encryptedXmlFile>
    <n0:base64EncryptedElementSignature>
        MqKeBqfHPjtMgIfopGEbL/NmRjiuaU1h0HMRVf7jlPkxZv1Ath+74AVcPHoDo2UjSqawWu1p5EZe6t6qKUnkFrsGUnX/ODPB2AXiJBRlE6/eC+N2kK2mwMZ6TRAXIv/zWB+ipNSNcLXTg4NvqCchfRNO75tpEIks29+YKVYi3eUvZz9HC9yCTvDH0qzvlaw02LXpKp+bNusAEDeyZPxExoL4MFtEN0bgSQGhnk88w+Ze3LbiY2F9J75vz6jFi3FQzKC8dvvFk8VDHtlDPVY6QuF4d2pEBH16cqb/g82m6JYd1qHvlwTn5qI2338J0IGoiFeIu5LnItoEnqZ/u3RS6A==
    </n0:base64EncryptedElementSignature>
</n0:data>`

Following is the contents of submission.xml:
_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by DavisRayM** [comment]
The `smart append` feature is a new feature implemented in `v1.17.0` of ODK Briefcase. I'm not quite sure if it required changes on our side, we might have to investigate the necessary changes required for it (if any).

**Comment by DavisRayM** [comment]
https://bitbucket.org/javarosa/javarosa/wiki/OpenRosaStatisticsAPI

**Comment by jwilliamrozelle** [comment]
I'm also experiencing this issue on `v1.18.0`, though without the smart_append.

Can't export submission uuidc603bb37-0e26-4548-ace5-77a25697933c of form ID odkr_encrypted_Test. Cause: ParseError at [row,col]:[1,283]
Message: Attribute "xmlns" was already specified for element "n0:data".

submission.xml:
`<n0:data encrypted="yes" id="odkr_encrypted_Test" instanceID="uuid:c603bb37-0e26-4548-ace5-77a25697933c" submissionDate="2021-03-05T05:17:36.809285+00:00" version="vksvsRVuyQ3XSvE6xrUox9" xmlns="http://www.opendatakit.org/xforms/encrypted" xmlns="http://opendatakit.org/submissions" xmlns:n0="http://www.opendatakit.org/xforms/encrypted"><n0:base64EncryptedKey>mBmtV0NswFXo+ZLzWfL7gqbVWnGDuEID8jX070uBC3AVhYiqh+RNkTAsEDViKlu8esj4NZ1fNQrCz1RmY5E3j/GsWFLon0mSD2r+xs6IldgUV8gdLhA6vmDnLIUiDbUc+4DLZA6nl8OoWP16OXEfSjW1Ve2DQHinwYPlMCKXX/RL6ocS7Yvuu19t3/q6lnYJ62WmfqlvBBd3u0O6pRtoUVO4MbvRF54OLE7RzI2BzVJVAJqIvEiBQcKXM8IQEJhbLp5p1I8lp2py4a6zvrhd5atwyGPWap7Y56im8s5enr4Ad7H3Ntx9PkGMZ2nL9bAiucuEcsfAW0/XjEMa64PpbQ==</n0:base64EncryptedKey><orx:meta xmlns:orx="http://openrosa.org/xforms"><orx:instanceID>uuid:c603bb37-0e26-4548-ace5-77a25697933c</orx:instanceID></orx:meta><n0:encryptedXmlFile>submission.xml.enc</n0:encryptedXmlFile><n0:base64EncryptedElementSignature>c7YAEIdPrvGP9XxKpBVq6BaG+N+neFDSXnfHYfDnhbcDPVdoJpkABX3dovpjAJAi9HMXIuV3DqhxOHaBlpUqPHnJTyx/qWSCoB+pjsbs7NZR8FpPwY4hjbazRpJ4urXRlfiokxUJl+uW+srAWYQHpmfM9/WnLQGspUx4T1sTOCWI3Gc+saTEhKVPezXUG0pfHKd/Bo9uiCXm/3xAzO84LO9BRDChKnyzUvOQB3PeaLxThVJUi9v5iJ3lRo4V0bpaZCZXQQCx93SZdWYoBIuYKR87b8PTa2hoacVUz1SlsfdBzPGCyiaTsN+Q9h7A7Eb/6EUYBaK51+wFs2+IbwJioA==</n0:base64EncryptedElementSignature></n0:data>`
