### ISSUE TITLE
GeoJSON endpoints does not return correct data

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#1800]
### Problem description
Making a get request to https://api.ona.io/api/v1/data/<form-id>.geojson gotten from https://api.ona.io/static/docs/data.html#geojson does not return the correct data for:
- geoshape fields
- geotrace fields
- geodata fields inside repeat groups

However it returns correct data for geopoint fields.

Example of incorrect data returned for geoshape field looks like this:
```{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": null,
            "properties": {
                "id": 57322026,
                "xform": 492041
            }
        },
        {
            "type": "Feature",
            "geometry": null,
            "properties": {
                "id": 58085369,
                "xform": 492041
            }
        }
    ]
}
```

While correct data returned for a geopoint field looks as follows:

```{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "GeometryCollection",
                "geometries": [
                    {
                        "type": "Point",
                        "coordinates": [
                            36.793912,
                            -1.295869
                        ]
                    }
                ]
            },
            "properties": {
                "id": 57401309,
                "xform": 492725
            }
        },
....
```

**Comment by FrankApiyo** [comment]
I created this public project to test out that endpoint https://ona.io/frankapiyo/113805. 
This issue can be reproduced by making requests to the following endpoints, passing project IDs from the above project: 

1. https://api.ona.io/api/v1/data/500202.geojson
2. https://api.ona.io/api/v1/data/500205.geojson
3. https://api.ona.io/api/v1/data/500204.geojson
4. https://api.ona.io/api/v1/data/500206.geojson

**Comment by WinnyTroy** [comment]
Hey @FrankApiyo , I had a look at this issue yesterday. 
From what I gather, the endpoint does serve correct data. I assume, its just not how you expected it.
Also, the requests that you are making may be wrong.

The documentation [here](https://api.ona.io/static/docs/data.html#geojson) details passing in `options` to retrieve geojson data on other fields
*the `With Options` segment*

When I try it on my end with a form that has all geo data fields i.e `geopoint(Point), geotrace(Polyline/LineString) and geoshape(Polygon)`
this would be the request I make
`https://api.ona.io/api/v1/data/513322/60549136.geojson`
which returns
```json
{
    "type": "Feature",
    "geometry": {
        "type": "GeometryCollection",
        "geometries": [
            {
                "type": "Point",
                "coordinates": [
                    36.744421,
                    -1.29943
                ]
            }
        ]
    },
    "properties": {
        "id": 60549136,
        "xform": 513322
    }
}
```
To get geojson data, for the geotrace field, I added this to the request
`https://api.ona.io/api/v1/data/513322/60549136.geojson?geo_field=my_geotrace`
which now returns
```json
{
    "type": "Feature",
    "geometry": {
        "type": "LineString",
        "coordinates": [
            [
                36.745623,
                -1.302819
            ],
            [
                36.750326,
                -1.299129
            ]
        ]
    },
    "properties": {
        "id": 60549136,
        "xform": 513322
    }
}
```
I do the same for the polygon field to return
`https://api.ona.io/api/v1/data/513322/60549136.geojson?geo_field=my_geoshape`
```json
{
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    36.747679,
                    -1.300717
                ],
                [
                    36.752386,
                    -1.305222
                ],
                [
                    36.751879,
                    -1.300642
                ],
                [
                    36.747679,
                    -1.300717
                ]
            ]
        ]
    },
    "properties": {
        "id": 60549136,
        "xform": 513322
    }
}
```

**Comment by FrankApiyo** [comment]
Thanks @WinnyTroy, I'm going to close this then.
