### ISSUE TITLE
Invalid variable name error when trying  to export a form with dynamic names/labels to .sav

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#1803]
### Problem description
.sav exports for form with dynamic name and labels in its choice sheet fail. The following error is logged to sentry: https://sentry.onalabs.org/ona/onadata/issues/70562/?query=is%3Aunresolved%20sav

### Steps to reproduce the behavior

You need a form with select one or select mutlitple fields whose names/labels are dynamic and look something as follows: #3:_${Q19member1}. Collect data with this form and then try to export to `.sav`

### Additional Information
Here's  information regarding valid variable names in spss: https://www.ibm.com/support/knowledgecenter/SSLVMB_23.0.0/spss/base/syn_variables_variable_names.html. There's no mention of  the `{` character. It probably should not be in a variable name.

**Comment by DavisRayM** [comment]
What would be the ideal way to handle dynamic labels when creating the `sav` export ? Would we need to just escape the special characters ? or would we need to replace the dynamic string with the correct value ?

CC: @ukanga

**Comment by DavisRayM** [comment]
Helpful resource: https://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.admin.ts.doc/doc/c0059609.html
