### ISSUE TITLE
Data submitted in format 'Mon-Year' are not converted to ISO Format

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1811]
### Environmental Information

- Onadata version: all

### Problem description

When data is submitted in the form `YYYY-MM-DD` it's returned in ISO Format on the `/data/<xform_id>` endpoint but when data is in the form `Mon-Year` it's not converted.

### Expected behavior

Data in the format `Mon-Year` should be processed the same as other date formats.

### Steps to reproduce the behavior

1. Create a form with the field `date` + an appearance attribute `month-year`
2. Submit data to the form using Enketo
3. Retrieve the data from `/data/<form_id>`

### Additional Information

Field XML:  `<date_collected>Oct-2018</date_collected>`

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by WinnyTroy** [comment]
I'm unable to replicate this after investigations and believe this to no longer be an issue
Below is an example of data collected with the appearance column set to `month-year`

![Screen Shot 2020-05-28 at 14 51 02](https://user-images.githubusercontent.com/11174326/83141216-f79f4d00-a0f7-11ea-8178-f450ea87193a.png)

Retrieving the data's xml also has the dates formatted even for data collected with the appearance column set to `year`
![datedd](https://user-images.githubusercontent.com/11174326/83141572-99269e80-a0f8-11ea-8477-20464230fb39.png)

**Comment by WinnyTroy** [comment]
Closing this issue, will re-open if its occurs once more
