### ISSUE TITLE
Instance _edited and _last_edited are not updated upon submission review.

### ISSUE THREAD

**Issue by lincmba** [onaio/onadata#1842]
### Environmental Information

- Operating System:
- Onadata version: 
- Python version:

### Problem description
When a submission review is made, the _submission_review field is updated with the new submission status. The _edited and _last_edited remains unchanged.
### Expected behavior
_edited and _last_edited should be updated upon submission review
### Steps to reproduce the behavior
1. Make a submission
2. Go to data endpoint, _edited is false, _last_edited is empty
3. Review the submission
4. Go to the data endpoint: _submission_review is updated, _edited and _last_edited remains unchanged.
### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by WinnyTroy** [comment]
@lincmba Im unsure of the problem this issue is to address.

The `_edited` field in the Instance model is updated when the contents/data collected within a submission are updated.
When a submission is reviewed, the contents of the original submission do not change.
Should we considered the review an edit? Is this something that we want to reconsider?

or is the aim of this issue to determine the time when a submission was last reviewed?
Running this through @ivermac @DavisRayM @ukanga

**Comment by ivermac** [comment]
@WinnyTroy makes a good point. Submission review objects and Instance objects are independent. Adding, editing or deleting a submission review doesn't affect an instance in any way hence i'm not sure if I fully agree with updating the instance when the submission review changes.

**Comment by DavisRayM** [comment]
I agree with the points made by @WinnyTroy, I don't believe we should update the `_edited` field of a submission unless the submission itself has been updated.

_If a way is needed to track when the last review was made, I'd suggest adding in a new metadata field for it..._

**Comment by lincmba** [comment]
@WinnyTroy @DavisRayM @ivermac valid points. 
If the `_edited` field should be updated IFF when the submission data (`json` or `xml` fields) has been updated then this should no longer be an issue.

However, if `_edited` is updated when other fields of the Instance model (i.e `has_a_review`)are updated then, this still is an issue based on this update made on submission_review save https://github.com/onaio/onadata/blob/master/onadata/apps/logger/models/submission_review.py#L17.

**Comment by lincmba** [comment]
Going to close this issue because, based on previous discussions, the `edited` and `last_edited` fields are to be updated only when the submission data is edited and not when a submission review is made.
