### ISSUE TITLE
Improvements to the "enketo" form endpoint

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#1855]
### Environmental Information

- Onadata version: `v2.3.5`

### Problem description

Currently we retrieve / generate the enketo single submission URL only when the `survey_type` query param is passed in with the value `single`. It would be nice if the `single_submission_url` was provided alongside the `preview_url` and `url` for the form.

_Also the `survey_type=single` query param seems to be raising issues on stage. We should investigate why this is happening and fix it_

<img width="1280" alt="Screenshot 2020-07-27 at 11 25 57" src="https://user-images.githubusercontent.com/25849009/88520225-f311ea80-cffb-11ea-8694-f4afe23adcb0.png">

### Expected behavior

I. The `single_submission_url` should be present in the response returned by `/api/v1/forms/<form_id>/enketo`
II. Should be able to retrieve the `single_submission_url` using `/api/v1/forms/<form_id>/enketo?survey_type=single`

### Steps to reproduce the behavior

I. Access `/api/v1/forms/<form_id>/enketo?survery_type=single`

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by ukanga** [comment]
Sentry issue: [ONADATA-4FE](https://sentry.onalabs.org/ona/onadata/issues/80895/?referrer=github_integration)

**Comment by ukanga** [comment]
We should also test submissions, seems we have a 404 on submissions from this kind of Enketo URL.
