### ISSUE TITLE
Records Get Duplicated after Editing 

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#1868]
### Environmental Information

- Operating System: OSX
- Onadata version: v2.3.7-rc
- Python version: 

### Problem description

When a user edits a record in Enketo the record gets duplicated upon reloading the **Table tab**. 

### Expected behavior

Records should not be duplicated after editing them in Enketo.

### Steps to reproduce the behavior

- Open the **Table tab** of a form.
- Click on the pencil icon to edit a record in Enketo.
- Submit the changes then reload the **Table tab**

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by DavisRayM** [comment]
Closed by #1869
