### ISSUE TITLE
Add time filter to messages API

### ISSUE THREAD

**Issue by lincmba** [onaio/onadata#1870]
### Environmental Information

- Operating System:
- Onadata version:
- Python version:

### Problem description
The Messages API does not support timestamp filters

### Expected behavior
The endpoint should have time filters aswell

### Additional Information
According to [this](https://github.com/onaio/onadata/issues/1791#issuecomment-601774261) issue comment, the following filters are supported: 
- target_type
- target_id
- verb
- user

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by moshthepitt** [comment]
Should we be concerned that we're essentially trying to implement or re-implement the data API endpoint?

In my mind the notifications endpoint is distinct and different from the data endpoint, and we should be wary of going down the road changing the notifications endpoint to work like any other endpoint.  Today its data, tomorrow it might be users or forms or something else.

**Comment by DavisRayM** [comment]
@moshthepitt I don't think this would be re-implementing the data API endpoint functionality. My understanding is that the `data` endpoint is mostly tied to the `Instance` model while the messaging `API` is tied to an Action(Could be a form update, project update, e.t.c)... As such it doesn't seem like a bad idea to be able to filter out certain actions/notifications based on a particular timestamp

**Comment by lincmba** [comment]
I agree with @DavisRayM, the notifications endpoint is an independent endpoint, and adding standard API functionalities to it isn't reimplementing another endpoint.

**Comment by moshthepitt** [comment]
Hmmm, @lincmba  could you describe the time-based filters that you mentioned in the PR description?

**Comment by lincmba** [comment]
@moshthepitt Since there is only one time field in the Action model, i.e timestamp, i'd expect the filters to be something like :
- `/?timestamp_gt=2018-11-22T12:57:11`
- `/?timestamp_gte=2018-11-22T12:57:11`
- `/?timestamp_lt=2018-11-22T12:57:11`
- `/?timestamp_lte=2018-11-22T12:57:11`
- `/?timestamp=2018-11-22T12:57:11`

**Comment by WinnyTroy** [comment]
This may be prioritized for the audit feature. 
Otherwise resourcing for this at the moment may not be guaranteed.
