### ISSUE TITLE
Add is_org SerializerMethodField to OrganizationSerializer

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#1898]
The UserProfile contains an `is_org` method which is used by clients(front end clients) to know whether the profile belongs to an organization or not. Organization Profiles do not have this field.

**Comment by DavisRayM** [comment]
Why would this be needed? I would assume if the client is accessing organizations it's self implied that the `is_org` field is True ??

**Comment by FrankApiyo** [comment]
https://github.com/onaio/onadata/pull/1890#issuecomment-692692100
