### ISSUE TITLE
Private forms not on FormList for authenticated users but available for anonymous users

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#1952]
### Problem description
Authenticated users with can view permissions are not able to open enketo preview links for private forms because the forms are not in their FormList when they go to `<onadata_url>/enketo/<form_pk>/formList?formID=<id_string>`

This is most likely caused by: https://github.com/onaio/onadata/blob/master/onadata/libs/filters.py#L77 which is used here: https://github.com/onaio/onadata/blob/24b743fc1acd13d7cab8e776a0afdbcd508ae679/onadata/apps/api/viewsets/xform_list_viewset.py#L45
### Expected behavior
Users with `can view` permissions on a form/project, should have the form on their formList so that they are able to see the form preview

**Comment by DavisRayM** [comment]
I would suggest we change the [permission required](https://github.com/onaio/onadata/blob/693b796be0fb4943142ef0bc70f375d5a2c92adf/onadata/libs/filters.py#L78) on the filter to `view_xform` as we don't necessarily need the user to have the permission to submit data to the form for them to be able to view it IMO... _Though I wonder if this would bring complications on platforms such as ODK Collect? As they would be able to download and create submissions but not submit data... Might be a user experience issue maybe?_
