### ISSUE TITLE
Cannot fill web form

### ISSUE THREAD

**Issue by parthibd** [onaio/onadata#1963]
### Environmental Information

- Onadata version: v2.4.7(2020-11-18)

### Problem description

I am trying to fill web form and unable to do so

### Expected behavior

Blank form should open with enketo
### Steps to reproduce the behavior

Just upload a form and go to enter data in web

### Additional Information

[Traceback](https://dpaste.com/28C77GFSH)

**Comment by parthibd** [comment]
@DavisRayM Can you please help me ?

**Comment by DavisRayM** [comment]
Hey @parthibd, do you have Enketo installed too? _Unable to open the traceback currently... please re-upload the traceback_

**Comment by parthibd** [comment]
I actually managed to solve this by installing Enketo :)
