### ISSUE TITLE
Internal server error raised when requesting CSVZip export

### ISSUE THREAD

**Issue by Janemesi** [onaio/onadata#1964]
### Problem description
When one runs this endpoint https://api.ona.io/api/v1/forms/28058/export_async?format=csvzip on a different browser tab,  a 500 error message is returned as shown on the attached screenshot:
<img width="953" alt="500export" src="https://user-images.githubusercontent.com/36330603/101457754-f6709780-3946-11eb-842b-22986610bcc4.png">

One will need to append json to the endpoint for the export_url to be generated. That is: https://api.ona.io/api/v1/forms/formid/export_async.json?format=csvzip

I have also noticed that one cannot download the export directly by clicking on the export_url. One will have to append the temp_token to the export_url to be able to download the generated export. That is: https://api.ona.io/api/v1/export/exportid.csvzip?temp_token=<temp token>

EDIT: Documentation for the messaging application `/api/v1/messaging` is also missing. That should be added along side the changes above

**Comment by DavisRayM** [comment]
I'm curious should we allow all the authentication methods currently supported on the other endpoints on this endpoint ? _Currently the endpoint only supports TempToken and the TempToken query authentication_

@ivermac @ukanga

**Comment by ivermac** [comment]
@DavisRayM I think we should; if we support one, I don't see the need to support the other.

**Comment by ukanga** [comment]
@DavisRayM Could this be a different issue other than authentication? See the sentry record I got https://sentry.onalabs.org/ona/onadata/issues/72502/.

**Comment by DavisRayM** [comment]
> @DavisRayM Could this be a different issue other than authentication? See the sentry record I got https://sentry.onalabs.org/ona/onadata/issues/72502/.

Yes, it seems like the `format` query param forces the endpoint to use the `CSVZipRenderer` or any other renderer with the given format... _This causes issues for the CSVZipRendere & SAVZipRenderer since they have no charset set for them..._. Trying to see if we can force that endpoint to use the JSONRenderer as that's the type of response we return from that endpoint...

Seems like this issue [was faced before](https://github.com/onaio/onadata/issues/1598) & [fixed](https://github.com/onaio/onadata/issues/1598)... looking into what caused it to re-surface

**Comment by ukanga** [comment]
The endpoint can return a ZIP file if one existed or CSV or XLS. The issue here may be how we handle a 404 request, and how we could change to a JSON renderer.

**Comment by DavisRayM** [comment]
> The endpoint can return a ZIP file if one existed or CSV or XLS. The issue here may be how we handle a 404 request, and how we could change to a JSON renderer.

That's weird... seems like the endpoint always returns a response with the content type `application/json`. Seems like it only returns [an Async result dict](https://github.com/onaio/onadata/blob/87d2f32ec5590cee0f4c5638df554b00435e3ac3/onadata/apps/api/viewsets/xform_viewset.py#L790-L798). With the `export_url` if the file is present

**Comment by ukanga** [comment]
The `?format=csvzip` picks the renderer. This  does not pick the JSON renderer. In https://github.com/onaio/onadata/blob/87d2f32ec5590cee0f4c5638df554b00435e3ac3/onadata/libs/renderers/renderers.py#L132 we could check for the response status code if it is a 404 and return a 404 response. Similar to https://github.com/encode/django-rest-framework/blob/d635bc9c71b6cf84d137a68610ae2e628f8b62b3/rest_framework/renderers.py#L730 but in this case 404.

**Comment by DavisRayM** [comment]
> The `?format=csvzip` picks the renderer. This does not pick the JSON renderer. In
> 
> https://github.com/onaio/onadata/blob/87d2f32ec5590cee0f4c5638df554b00435e3ac3/onadata/libs/renderers/renderers.py#L132
> we could check for the response status code if it is a 404 and return a 404 response. Similar to https://github.com/encode/django-rest-framework/blob/d635bc9c71b6cf84d137a68610ae2e628f8b62b3/rest_framework/renderers.py#L730 but in this case 404.

Ahh okay, didn't know this still occurs for 404s. How about scenarios where the response status code is 202 ? _This error seems to occur even when the async task has been queued_

```
    def test_export_csvzip_form_data_async(self):
        with HTTMock(enketo_mock):
            self._publish_xls_form_to_project()
            view = XFormViewSet.as_view({
                'get': 'export_async',
            })
            formid = self.xform.pk

            request = self.factory.get(
                '/', data={"format": "csvzip"}, **self.extra)
            response = view(request, pk=formid)
            self.assertIsNotNone(response.data)
            self.assertEqual(response.status_code, 202)
            print(response.data)
            # Ensure response is renderable
            response.render()
```

**Comment by ukanga** [comment]
With status 202 it does mean we need to return the JSON as well since that provides progress updates. We can check for both statuses or we need to check for the content or compare the content with the requested format and handle it gracefully.
