### ISSUE TITLE
File names for CSV Zip exports are not set to the form title

### ISSUE THREAD

**Issue by bkimondiu** [onaio/onadata#1968]
### Environmental Information
Production

### Problem description
When exporting data using the CSV Zip format, the name of the exported CSV file seems to switch between `data.csv` and `<form_title>.csv`. 

### Expected behavior
Below are findings from an investigation done by @WinnyTroy 

> We use python's [tempfile module](https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile) to generate this export file name in our platform [here](https://github.com/onaio/onadata/blob/master/onadata/libs/utils/export_builder.py#L753).
> The file name is ideally meant to be generated from the xls file name.

### Steps to reproduce the behavior
1. Ensure you have a form in Ona with data
2. In the **Export data** section of the form's **Overview** tab, prepare an export link with the **File type** as _CSV Zip_.

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by DavisRayM** [comment]
We don't use form titles to generate export filenames; This is most likely something we can look into but I do not see the urgency/benefit of doing so...

The CSV Zip export file name is usually set to `<form_id_string>_<timestamp>.<extension>`; The only reason this would occur is if the id_string of the form was `data` and if so I'd like to believe this is how the functionality was intended to function.

Code that names the file can be found [here](https://github.com/onaio/onadata/blob/b8f3c320d21c13e188c065501ac3d7c0bf1f5836/onadata/libs/utils/export_tools.py#L224-L269)
