### ISSUE TITLE
Access API key UI feature not working

### ISSUE THREAD

**Issue by larshelge** [onaio/onadata#1976]
### Environmental Information

- Onadata version: ona.io, January 6, 2021.

### Problem description

The UI for retrieving your API is not working apparently.

### Expected behavior

The UI for retriving your API key should show the API key when the current password is entered.

### Steps to reproduce the behavior

* Go to Settings > API
* Enter your password and click **Confirm password**.

Notice that the API request made by the UI is:

    https://ona.io/{client}/*configs*-api-key

The \*configs\* part of the URL might be unintentional.

**Comment by DavisRayM** [comment]
Kindly re-try and check if this is fixed. If it's not kindly report this to Ona Support support@ona.io
