### ISSUE TITLE
Data Endpoint: Support pagination of XML Response

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#2000]

**Comment by gstuder-ona** [comment]
One option that would meet ETL requirements would be a query parameter to the paginated JSON endpoint which just attached the XML as text in a JSON field.  The paginated XML would need to be searchable in the same way as the JSON, so maybe this is a fast workaround.

**Comment by gstuder-ona** [comment]
As discussed in the product meeting, the requirements for the paginated xml endpoint would include pagination by the last_modified field, which is not included in the xform form instance xml - this would need to be attached as xml metadata.  Also, the form_id is not included in the xform instance xml - this also would need to be attached as metadata.

Summary:  What is needed is:

form id
form last modified
xform form submission (which should include form version)

**Comment by gstuder-ona** [comment]
@DavisRayM what's up on stage-api looks good, as we built more of the pipeline we realized we also need to know the latest server time.  Could we wrap the batch of results like:

<root><submission-batch serverTime="[iso]"><submission-item ...></submission-item></submission-batch></root>

This will allow us to be much more efficient pulling the latest submissions from a form, as now we're never quite sure how recent the timestamps are compared to where the server time actually is.

**Comment by gstuder-ona** [comment]
I took a quick look - I'm not sure we can use the endpoint as is?  There seems to be some issues in result ordering - here's an example:

https://api.ona.io/api/v1/data/558517.xml?query={"_date_modified":{"$gt":"2000-01-22T11:42:20"}}&limit=3
```
<submission-batch serverTime="2021-03-12T12:30:02.993349+00:00">
<submission-item created="2020-11-19T07:44:24.301684+00:00" formVersion="202011190742" lastModified="2021-03-11T12:31:58.498648+00:00" objectID="69885102">
...
</submission-item>
<submission-item created="2021-01-15T08:06:54.031132+00:00" formVersion="202011190801" lastModified="2021-03-11T12:31:59.005477+00:00" objectID="72915824">
...
</submission-item>
<submission-item created="2021-01-15T08:11:15.064601+00:00" formVersion="202101150803" lastModified="2021-03-11T12:31:58.979827+00:00" objectID="72915896">
...
</submission-item>
</submission-batch>
```

Note that what is returned is the later modified entries, not the first.  Also, even in the batch, the ordering is not consistent.  The ordering is also not consistent with the JSON endpoint:

```
[{
	"_id": 69885102,
  ...
	"_date_modified": "2021-01-22T08:50:58",
  ...
}, {
	"_id": 72915824,
  ...
	"_date_modified": "2021-01-15T08:06:54",
  ...
}, {
	"_id": 72915896,
  ...
	"_date_modified": "2021-01-15T08:11:15",
  ...
}]
```
