### ISSUE TITLE
Ability to search by last modified date for both new and edited onadata form instances

### ISSUE THREAD

**Issue by gstuder-ona** [onaio/onadata#2001]
## Suggested Feature / Enhancement
To my understanding, the last_modified field is not exposed for querying in the v1 data/ api - this makes it awkward to paginate ona data form instances by creation or update time: 

https://github.com/onaio/onadata/blob/20a4dece8fc7bee435e3512266649deec5200c66/onadata/apps/logger/models/instance.py#L486

It's possible to paginate by submission time or last edited time separately, for example:
https://api.ona.io/api/v1/data/558517?query={%22_last_edited%22:{%22$gte%22:%222020-01-19T11:40:06%22}}

But the last_edited field only exists for form instances that have actually been edited, so no unedited instances appear, and merging two sets of differently-paginated results is pretty complex to get efficient and correct.

Also, from my understanding of the code the last_modified field is tied to the data structure and auto-populated by django libraries, which may make it more robust vs the last_edited which seems to be linked to another history data structure.  It may be more natural to use for ETL.

If there's functionality I'm missing in this direction it would definitely be good to know, a request for discussion.

## Benefits of implementing the feature/enhancement
Much easier to paginate form instance data by modification time, easier to ETL.

**Comment by pld** [comment]
@FrankApiyo @ivermac can you please link to or update (if it's not there) the docs (and provide some details here) on what `last_edited` represents?

Also, do you know if this timestamp is determined when the instance is created in Django or when it's inserted in the DB? My understanding is this is stored in django as a `NOW()` directive for the DB and the time is set when the instance is inserted in the DB, but please correct me if that's wrong.

**Comment by gstuder-ona** [comment]
@pld I was looking at https://docs.djangoproject.com/en/3.1/ref/models/fields/#datefield and https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.timezone.now - django controls the timezone, and there's a utility function that gets used to generate the datetime.  Could still be misunderstanding things but I'm pretty sure that must mean django is generating the timestamps.  Fortunately it seems like our timestamps are GMT since the common.py onadata config seems to have USE_TZ as America/New York.

**Comment by moshthepitt** [comment]
@DavisRayM ^^

**Comment by DavisRayM** [comment]
The `last_edited` date is usually set in the codebase during the creation of the instance history object([code block](https://github.com/onaio/onadata/blob/263bcb442781f3c339959523cce19b9402ed4d3f/onadata/libs/utils/logger_tools.py#L88-L101)) and usually represents when an InstanceHistory object was last created([ref](https://github.com/onaio/onadata/blob/master/onadata/apps/logger/models/instance.py#L493))...

The field that's usually updated by Django before being inserted(pre_save) into the DB is the `last_updated` field. _My understanding is this field is usually set to timezone.now() before the save function is called.... I don't believe Django uses the `NOW()` function/directive for the DB_

**Comment by gstuder-ona** [comment]
As discussed in the product meeting, for the purposes of ETL the more relevant timestamp is last_updated, as this will reflect every change that an instance has vs just those generating onadata instance history objects.

**Comment by DavisRayM** [comment]
Currently, the `last_modified` date isn't added into the JSON response of the instance. Should we also add it into the JSON response as metadata while adding the ability to search using the field? _I'm leaning towards adding it into the JSON for this case...._

**Comment by gstuder-ona** [comment]
@DavisRayM yes, plz - it'd be pretty confusing not to IMO.

If you're normalizing stuff, my other comment is that the date_created field, i.e. _submission_time, should be part of the submission-item XML wrapper also.  Generally it's just nice to have creation time and modified time as metadata in both JSON and XML.

**Comment by ivermac** [comment]
@DavisRayM sounds good to me to have `last_modified` in the JSON response

**Comment by ukanga** [comment]
@gstuder-ona  Note, we do not dynamically generate the XML data, we simply supply what was collected from the field, hence no metadata is injected at runtime. We cannot modify the XML with metadata at rest as well since that is likely to make the XML lose the link to the XForm definition and as a result, edits may fail, ODK Briefcase or pull by other ODK aggregate servers become problematic.

I am okay adding the metadata to JSON. I say no to metadata being added to the XML.

**Comment by gstuder-ona** [comment]
@ukanga this isn't metadata being added to xml - this is the wrapper around the xml (which already includes the metadata of last_modified).  Agree we shouldn't inject anything into the xform data.

**Comment by DavisRayM** [comment]
> @ukanga this isn't metadata being added to xml - this is the wrapper around the xml (which already includes the metadata of last_modified). Agree we shouldn't inject anything into the xform data.

This [PR](https://github.com/onaio/onadata/pull/2005) might give a bit more context on the added wrapper @ukanga; _Recently added with the changes to enable the XML data to be returned from the `/api/v1/data/<id>.xml` endpoint

**Comment by ivermac** [comment]
@ukanga I'd like to think @gstuder-ona is referring to work we did last week - https://github.com/onaio/onadata/pull/2005 - where we introduced xml rendering for data endpoint

**Comment by ukanga** [comment]
I am very aware of that unless perhaps the implementation is different from what I had envisioned. Which I see now is very different from what I had expected when we talked about this.

**Comment by gstuder-ona** [comment]
In any case, the second ask is this: https://github.com/onaio/onadata/pull/2005/files#diff-8bfe894c27af0b1fa7140fa6a05694063742cc1f0dbbd660ab61f97e4259e010R122 - add a single line `'@created': instance.date_created.iso_format(),`

I leave it to the onadata team if that's a tiny enough change to do as part of this or needs to be rescheduled
