### ISSUE TITLE
API queries on time do not interpret $gt/$gte bounds correctly

### ISSUE THREAD

**Issue by gstuder-ona** [onaio/onadata#2004]
### Environmental Information

- Onadata version:
api.ona.io/v1

### Problem description
Requesting data $gt a time bound *includes* data with exactly that time:

```
https://api.ona.io/api/v1/data/558517?query={%22_submission_time%22:{%22$gt%22:%222020-11-19T07:44:24%22}}&limit=1&sort=_submission_time

[{"_id": 69885102, ..., "_submission_time": "2020-11-19T07:44:24"}]
```

The behavior persists even when adding a time zone (`2020-11-19T07:44:24Z`) or milliseconds to the date (`2020-11-19T07:44:24.999Z`), and can only be changed by bumping up the final minute (in this case to :25).

The reverse problem occurs with `$lt/$lte queries queries:
```
https://api.ona.io/api/v1/data/558517?query={%22_submission_time%22:{%22$lte%22:%222021-01-22T11:42:20%22}}&limit=1&sort=-_submission_time

[{"_id": 73050523, ..., "_submission_time": "2021-01-19T11:40:06"}]
```
... even though a form with that exact submission time exists in the database.

### Expected behavior

$gt/$gte/$lt/$lte would exclude/include results appropriately at exact time boundaries.

### Additional Information

We can try to work around this but it's very confusing behavior, easy to cause missed-data bugs

**Comment by LeonRomo** [comment]
Tried recreating the issue by testing it locally. Seems to be working as expected. Below are the steps taken when investigating the issue. 

1. Run local server
2. Open postman
3. Enter the request URL for displaying all the data in the target form `http://localhost:8000/api/v1/data/10?fields=["_id", "_submission_time"]`
4. Query submissions collected before specific date `http://localhost:8000/api/v1/data/10.json?query={"_submission_time":{"$gt": "2015-01-31"}}`
5. Getting a specific timeframe `http://localhost:8000/api/v1/data/10?query={"_submission_time":{"$lt": "2015-03-09T13:34:05Z"}}&fields=["_id", "_submission_time"]` using `$lte/$lt,$gt,$gte`

Below find attached images of the results

1.  `http://localhost:8000/api/v1/data/10?query={"_submission_time":{"$lt": "2015-03-09T13:34:05Z"}}&fields=["_id", "_submission_time"]`
![Screenshot from 2021-11-05 11-27-22](https://user-images.githubusercontent.com/48680199/140480974-4ec08b01-1288-44d1-9ae4-f981d75c98fc.png)
.
