### ISSUE TITLE
Add available export options to the API documentation

### ISSUE THREAD

**Issue by bkimondiu** [onaio/onadata#2038]
Update the API documentation by adding the available export options e.g. `do_not_split_select_multiples`, `include_labels_only`, `show_choice_labels`.

**Comment by DavisRayM** [comment]
After further investigation it seems that the available export options are already documented. They are documented [here](https://stage-api.ona.io/static/docs/forms.html#csv-and-xls-exports-without-group-name-prefixed-to-the-field-names); each option has it's own separate section.... scrolling down from the above link should show you all the options and their examples.

Going to close this issue for now

CC: @bkimondiu @denniswambua @WinnyTroy
