### ISSUE TITLE
Upgrade Celery Dependency to v5.*

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#2048]
### Environmental Information

- Onadata version: v2.5.3

### Problem description

The celery version we are currently using has a few [bugs](https://github.com/celery/celery/issues/6370) when using celery multi start . It doesn't actually pass the -A argument to the workers. 

### Expected behavior

- The `-A` argument should be passed to the started celery workers

### Steps to reproduce the behavior

- Run `pip install -r requirements/base.pip`
- Start celery workers with celery multi `celery mutli start celery xls_node -A onadata.celery -O fair`
- Check `ps aux | grep celery`; You'll notice the celery workers don't have the `-A onadata.celery` arguement

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by WinnyTroy** [comment]
This could track upgrading all dependancy packages i.e django 3, DRF packages
