### ISSUE TITLE
Automate retrieving list of collaborators for Orgs and Projects

### ISSUE THREAD

**Issue by WinnyTroy** [onaio/onadata#2051]
## Suggested Feature / Enhancement
MoDa have severally requested to have a list of project collaborators fetched.

The logic used to manually do this at the moment is
- Get users from the projects endpoint `https://api.ona.io/api/v1/orgs/<org name>` and filter out the organization.
- They will be the org members and for collaborators, we specify get users from the projects endpoint `https://api.ona.io/api/v1/projects.json?owner=<org name>` then filter out organizations to remain with a list of users(collaborators)

It would be better to have an automated way of doing this.

## Suggested implementation plan(Steps to be taken to implement feature)
- Management Command
- Query Param introduced in the Project and Org endpoints that can filter this data
- Utility function to call from django shell

**Comment by DavisRayM** [comment]
_For the organization members, I believe `/api/v1/orgs/<org_name>/members` gives the required information; Returns a list of usernames though it doesn't return the roles it seems._

I'll add a management function to return more verbose information though
