### ISSUE TITLE
Enhance Delete Submissions Functionality

### ISSUE THREAD

**Issue by denniswambua** [onaio/onadata#2065]
## Suggested Feature / Enhancement
We can delete multiple of submission at once but this is not good for a large dataset.  
- [x] Test out deleting 10,000 records with the current sync method.
- [ ] If necesarry implement async delete 
- Ruled out async and instead leveraged django [queryset.update()](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.update) utility. 
- We have not specified a batch size value for the update method, instead, we make use of the default, which is to update all objects in one batch.
- [x] For delete all, We can add a flag to the endpoint that uses an update query to do the soft delete.
 
## Benefits of implementing the feature/enhancement
Support delete of ten of thousand of submission at once.

**Comment by WinnyTroy** [comment]
Endpoint being hit is the data endpoint `api/v1/data/<form_id>`.
Method is `DELETE`
Parameters are - `49881105,49881104,49881103,49880988,49880981,49880980,49880979`

Test request made
```code
curl --location -g --request DELETE 'https://api.ona.io/api/v1/data/436336' -d 'instance_ids=<10,000 comma separated sub ids>'  -u 'username:password' -w %{time_connect}:%{time_starttransfer}:%{time_total}
```

API request to delete 10, 000 submissions fails with:
```code
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

The timed-out result yielded the following time durations:
```code
%{time_connect}:    %{time_starttransfer}:         %{time_total}
0.153122:           0.457035:                      300.985191
0.152892:           0.455505:                      300.903115
```
_**N.B**_
Using the [curl documentation](https://curl.se/docs/manpage.html)
**Time_connect** - The time, in seconds, it took from the start until the TCP connect to the remote host (or proxy) was completed.
**Time_starttransfer** - The time, in seconds, it took from the start until the first byte was just about to be transferred. This includes time_pretransfer and also the time the server needed to calculate the result.
**Time_total** - The total time, in seconds, that the full operation lasted.
