### ISSUE TITLE
Use ISO date formatting in data exports

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#2071]
### Environmental Information

- Onadata version: v2.5.4

### Problem description

When data with date questions is exported from Ona, the date format gets changed from the ISO date format `yyyy/mm/dd` to `dd/mm/yyyy`. The `dd/mm/yyyy` format gets imported back to Ona when uploading the downloaded data. This results in the date fields being populated as nulls in ETLs. 

### Expected behavior

Dates should be exported in the same date format that is stored/saved in Ona i.e. `yyyy/mm/dd`. 

### Steps to reproduce the behavior
- Export data from a form that has date questions/fields. 

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by DavisRayM** [comment]
@faith-mutua Is there a particular export format that does this ? Tested it out with CSV Exports and the date field doesn't seem to be modified. Still stays in the same `YYYY-MM-DD` format that's present in the API

**Comment by DavisRayM** [comment]
The functionality exports the date in the same format the API returns; this issue was caused by excel auto-formatting the date column.
