### ISSUE TITLE
Paginated XML endpoint serializes invalid XML for file attachments

### ISSUE THREAD

**Issue by gstuder-ona** [onaio/onadata#2072]
### Environmental Information

- Onadata version:
stage.ona.io

### Problem description
As mentioned here: https://onaio.slack.com/archives/C04DRCMRD/p1620306800044000

`https://stage-api.ona.io/api/v1/data/2632/145875.xml` - this gives you

```
<q0_08_passport_pic type="file">20210109_102230-9_6_2.jpg</q0_08_passport_pic>
```

`https://stage-api.ona.io/api/v1/data/2632.xml?query={"_date_modified": {"$gt": "2021-05-06T06:20:50Z"}}&limit=1`  - this gives you:

```
    <q0_08_passport_pic type="file"><#text>20210109_102230-9_6_2.jpg
    </#text>
</q0_08_passport_pic>
```
(the paginated result is centered on the same 145875.xml entry)

gregs  45 minutes ago
the ETL fails as the <#text> tag isn't valid XML and so can't be parsed.  We can hack something to catch this, but it would be good understand exactly what's going on here and if it's fixable on OnaData side anytime soon.

### Expected behavior

The paginated XML endpoint should return valid XML identical to the individual XML endpoint.

### Steps to reproduce the behavior

See above.

### Additional Information

Seems to be a serialization issue, `<#text>` is the name for HTML DOM nodes.

**Comment by gstuder-ona** [comment]
@DavisRayM I'm sure this will take a dev cycle and QA to fix, but if you're able to give us a good guess as to whether `#text` is the only problem or there are other DOM nodes to suppress it'd help us get better QA turnaround

**Comment by DavisRayM** [comment]
> @DavisRayM I'm sure this will take a dev cycle and QA to fix, but if you're able to give us a good guess as to whether `#text` is the only problem or there are other DOM nodes to suppress it'd help us get better QA turnaround

After further investigation I believe the `#text` element is the only problem... Working on removing invalid XML elements from the XML in general
