### ISSUE TITLE
Include name for textit services

### ISSUE THREAD

**Issue by RayceeM** [onaio/onadata#2075]
### Environmental Information
All

- Onadata version:

### Problem description
Other services i.e google sheet have the name of the google sheet on payload but not for textit services.

### Expected behavior
Include a name/title for a flow or 
### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by DavisRayM** [comment]
For most of the other services we usually get the associated reasources name from the POST request made to create the rest service. In this case I'd suggest the addition of a new `flow_name` or `flow_title` parameter in the payload required to create the rest service.

[Google sheets payload
](https://stage-api.ona.io/static/docs/restservices.html#adding-google-sheet-sync)
[TextIT payload](https://stage-api.ona.io/static/docs/restservices.html#adding-google-sheet-sync)
