### ISSUE TITLE
Can't get a list of chart field endpoints

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#2089]
### Environmental Information

- Onadata version: 2.5.5

### Problem description

The endpoint `https://api.ona.io/api/v1/charts/{formid}` fails with the error `400 Bad Request`

### Expected behavior

A user should be able to view a list of chart field endpoints for a specific form or dataset using the endpoint `/api/v1/charts/{formid}`

### Steps to reproduce the behavior

Try getting a list of chart field endpoints using `https://api.ona.io/api/v1/charts/{formid}`

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by LeonRomo** [comment]
Closed by another PR
