### ISSUE TITLE
Error when grouping chart fields

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#2090]
### Environmental Information

- Onadata version: 2.5.5

### Problem description

Grouping chart fields fails with a `404 Not Found`

### Expected behavior

A user should be able to group a chart field by other fields in a form using the endpoint `/api/v1/charts/{formid}.{format}?field_name=field_name&group_by=field1,field2`

### Steps to reproduce the behavior

Try grouping a chart field with `/api/v1/charts/{formid}.{format}?field_name=field_name&group_by=field1,field2`

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by LeonRomo** [comment]
The issue is closed because it has been resolved and working on master
