### ISSUE TITLE
Sorted submissions are not paginated correctly

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#2108]
### Environmental Information

- Onadata version: `v2.5.7`

### Problem description
Submissions on data endpoint are not paginated correctly when you pass `sort` query parameter

Without `sort` query parameter:

![Screenshot from 2021-06-22 12-47-08](https://user-images.githubusercontent.com/25260439/122914784-ad70b580-d363-11eb-9e6b-bcae067db8ae.png)

With `sort` query parameter:
![Screenshot from 2021-06-22 12-46-51](https://user-images.githubusercontent.com/25260439/122914882-cda07480-d363-11eb-8b62-f6beceee26c1.png)

### Expected behavior
Pagination query parameters should work the same with or without the order query parameters

**Comment by WinnyTroy** [comment]
From testing this, I would like to note the following:

The API returns paginated and sorted data (Ascending and Descending) from these requests:
`https://api.ona.io/api/v1/data/381370.json?page_size=3&page=1&sort={"_submission_time":-1}`
`https://api.ona.io/api/v1/data/381370.json?page_size=3&page=1&sort={"date_created":-1}`

Sorting data from a specific field within the submitted data occurs successfully from this request as seen in the docs [here](https://ona.io/static/docs/data.html#example-of-ascending-sort)
`https://api.ona.io/api/v1/data/381370.json?sort={"date_created":-1}`

Caveats from this query are:
- The field you are passing in the request MUST exist in the submitted data
- This does not return a paginated response

To return a defined number of submissions, say 10, of specific fields within the submitted data in a sorted manner, the request to use would be
`https://api.ona.io/api/v1/data/381370.json?start=1&limit=2&sort={"_submission_time":-1}&fields=["_submission_time", "_id"]`
The `start` and `limit` query params have been detailed [here](https://ona.io/static/docs/data.html#get-json-list-of-data-end-points-using-limit-operators)

I'll be adding tests to confirm the above and updating the documentation appropriately
