### ISSUE TITLE
Ensure basic and digest Authentication works in data endpoint

### ISSUE THREAD

**Issue by denniswambua** [onaio/onadata#2125]
### Environmental Information
production

- Onadata version:
2.5.7

### Problem description
Basic an digest authentication are failing on `api/v1/data/<form_id>.csv` endpoint.

### Expected behavior
Basic and digest authentication should work and be tested on the power bi integration

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by WinnyTroy** [comment]
I've tested out the data endpoint against the two authentication methods. Items noted:
- Requests are authenticated successfully with both basic and digest authentication.
- Private forms accessed with no authentication fails.
- Public forms accessed with no authentication returns data successfully.

Kindly find attached screenshots showcasing the above scenerios:
1. Public form accessed with basic auth returns data successfully
![basic_auth_public_form](https://user-images.githubusercontent.com/11174326/128354931-859b404d-b2f4-4e39-b716-0c10cdfbdd91.png)


2. Public form accessed with Digest auth returns data successfully
![digest_successful](https://user-images.githubusercontent.com/11174326/128355021-88e2fe80-1228-4f97-99d4-eae25ca4f3fb.png)


3. Private form accessed via Basic auth returns data successfully
![basic_auth_private_form](https://user-images.githubusercontent.com/11174326/128355119-188f6cdd-50f2-42d7-b6ba-33aca39890dc.png)


4. No authentication passed to access private form returns no data
![no_auth_private](https://user-images.githubusercontent.com/11174326/128355176-e7f863b0-bedb-48f2-bf29-b654b10c3bbb.png)

5. No authentication passed to access public form returns data successfully
![no_auth_successful_public_form](https://user-images.githubusercontent.com/11174326/128355217-52fa5735-000c-45f0-a48e-e0722ba5a017.png)
