### ISSUE TITLE
Update exports when records are deleted

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#2130]
### Environmental Information

- Onadata version: v2.5.8

### Problem description

Deleted records for forms that had data exports generated before the deletion occurred are not being removed from the created exports. It appears that data exports are not being updated because when the user tries to prepare an export after deleting records, no new export is generated. The user is redirected to the previously created export which includes the deleted records. This issue is affecting other functionalities like, pulling data in Ona R and pulling data from linked datasets where deleted records in the linked form are still available.

### Expected behavior

When records are deleted from a form, any exports generated before the deletion happened should be updated to remove the deleted records. We could also have a new data export generated altogether in such cases. 

### Steps to reproduce the behavior
- Create a data export in any of the exports formats
- Delete some records from the form
- Try creating a new export in any of the formats used in step 1
- Use this [test form](https://docs.google.com/spreadsheets/d/1-7exP8rhR3YQLI2GxyhhK2nXd6P4tiD7ZSgy7WzX0ek/edit#gid=41563628) that's pulling data from this other [test form](https://docs.google.com/spreadsheets/d/1Th_3VBq6OBuxxS5DciqBW-ZWvrGFeKZf2-gZzHP-IJ8/edit#gid=940000897). 

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by faith-mutua** [comment]
@DavisRayM Exports are not being updated when records are deleted. The deleted data is still accessible in old/previously generated exports and linked datasets even after deleting the connection and linking the form/dataset again. The refresh/update only happens when new records are submitted to a form.

**Comment by DavisRayM** [comment]
Main cause of this seems to be the way the API deletes instances; The API deletes instances via the `update` Queryset method which doesn't call the `save` function and thus doesn't update the instances `date_modified` field which is used to determine whether a new export needs to be generated. PR #2132  solves the issue

_TL;DR: Issue was caused because the API doesn't update the `date_modified` date when deleting instances_
