### ISSUE TITLE
High request times for retrieval of statistics & data on forms with a large number of contributors and submissions

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#2163]
## Current situation

The statistics endpoint `/api/v1/stats/submissions` alongside the data endpoint `/api/v1/data` (when used with start and limit query params) and media count endpoints currently take a lot of time(Around 1 - 3 minute depending on server load) to compute the statistics of a given form... This leads to some unpleasant user interactions.

We should look into a way to decrease the amount of processing/query time we take for such requests in order to speed up the request times as the current wait time is too long IMO

![image](https://user-images.githubusercontent.com/25849009/139197211-9e5e71fc-f3d5-47cc-b57d-1bf58d7d1cb6.png)

## Suggested approaches

- Calculate submission stats as submissions are made(Async task post submission perhaps?) & save the statistics to cache

**Comment by alepietrobon** [comment]
keep me posted on this, guys. Clients are onto it.  Thanks! 
![image](https://user-images.githubusercontent.com/8207502/142009362-d9902190-b234-4368-afab-7df740930c3a.png)

**Comment by DavisRayM** [comment]
Closing this issue; Kindly re-open if review fails
