### ISSUE TITLE
Increase the length of characters in share project serializer

### ISSUE THREAD

**Issue by samwata** [onaio/onadata#2308]
We have users import feature where you can import collaborators from one project to another. In this case if you have many users in a project and you try to import those users to a different project you get error `Ensure this field has no more than 255 characters` as shown in the attached screenshot.
It seems that the validation check that sum of the characters of all users in the list is not more than 255 characters.
We will like to add this limit when we are using users import feature
![image](https://user-images.githubusercontent.com/23456184/186087424-937ee0f9-1511-4724-8627-fa44e545aa63.png)

**Comment by KipSigei** [comment]
@DavisRayM @ukanga Seems the username field in [ShareProjectSerializer](https://github.com/onaio/onadata/blob/main/onadata/libs/serializers/share_project_serializer.py#L39) expects a comma-separated list of usernames, and the Char limit is set to 255. Should we increase the limit or remove it?

**Comment by DavisRayM** [comment]
@KipSigei I believe we should remove it; The `max_length` constraint is probably a left over constraint from when the `ShareProjectSerializer` did not support bulk sharing.... I don't see the need to constraint the field at the moment; Perhaps a max amount of users one can share too during the process but the length should be unlimited or high enough to support a lot of users IMO
