### ISSUE TITLE
Error trying to remove user from an ona data project

### ISSUE THREAD

**Issue by obanda** [onaio/onadata#2328]
### Environmental Information

- Onadata version:

### Problem description
I get an error when i try to remove a user (William Mucheru: [wmucheru](https://ona.io/wmucheru))from the MESH ona project
### Expected behavior
I expect the user to be removed
### Steps to reproduce the behavior
Access the MESH project members URL here : https://ona.io/organizations/transtecsomalia/members
Remove the member (William Mucheru: [wmucheru](https://ona.io/wmucheru)) from the project
### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._
<img width="539" alt="image" src="https://user-images.githubusercontent.com/2913805/198203786-0782148e-7da6-4a02-9437-bcac0f831b42.png">

**Comment by ciremusyoka** [comment]
@obanda  the user is not active. You can activate the user, remove the user and deactivate again.
