### ISSUE TITLE
Performance hit comparison between filtering/sorting vs retrieving submissions at a time

### ISSUE THREAD

**Issue by machariamuguku** [onaio/onadata#2332]
- Based on the conversation here https://github.com/onaio/canopy/issues/2908#issuecomment-1302094555
- Context:
	- Sorting and filtering on the data endpoint creates a performance hit on ona data for forms with many submissions (100k+)
	- E.g `https://api.ona.io/api/v1/data/form_id.json?page=1&page_size=2000&query={"_date_modified":{"$gte": "2020-10-31T00:39:19"}}&sort={"_date_modified":-1}`
	- Performance issue https://github.com/onaio/canopy/issues/2872
	- The alternative solution suggested is to use the messaging endpoint
		- E.g ` https://api.ona.io/api/v1/messaging.json?target_type=xform&target_id=form_id&timestamp__gte=2020-11-03T06:07:46.576690-04:00&page=1&page_size=2000`
		- Auto sorted by timestamp
		- Then query for all submissions corresponding to these messages 
			- Either one at a time or by composing a single data endpoint request with all the submission id's in a list
			- E.g `https://api.ona.io/api/v1/data/target_id.json?page=1&page_size=2000&query={"$or": [{"_id": "submission_id_1", "_id": "submission_id_2", "_id": "submission_id_n"}]}`
- We want a load testing QA on 
	1. The performance hit comparison between the two approaches (sort and filter on data endpoint vs filter on messaging endpoint)
	2. If there is a limit on the url query parameter size for data endpoint (assuming n number of submissions)
	3. For a form with at least 100k submissions but ideally more than 500k

**Comment by machariamuguku** [comment]
cc @alepietrobon @KipSigei

**Comment by alepietrobon** [comment]
thanks @machariamuguku . @Mstjamush, please let us know how we can get this scheduled. Thanks

**Comment by Mstjamush** [comment]
This has been noted.
@faith-mutua and I will touch base to see how to assist

**Comment by faith-mutua** [comment]
@machariamuguku @Mstjamush @alepietrobon The three endpoints have proven to be able to handle huge loads of submissions especially when the loads are being generated by one user. Below is a breakdown of the load test results. All tests were scripted in locust.io using python and run using locust. You can find them on [this repo](https://github.com/onaio/onadata-load-tests/tree/main/dataEndpoint) under the folder titled `dataEndpoint`

- Fetching data using the submission IDs is capable of handling up to but not limited to 15,000 submission IDs appended to the URL request in a list.

- Sorting and filtering on the data endpoint allows a user to filter over 100,000 submissions in one request in a form with over 300K submissions. A performance hit is observed when the load increases up to 200K submissions per request. The requests in this case are quite slow, one request gets processed after 10 minutes with such a huge load.

- Sorting and filtering on the messaging endpoint allows a user to filter over 100,000 submissions in one request in a form with over 300K submissions. There's a performance hit when the load increases up to 200K submissions per request. The requests are quite slow, one request gets processed after 10 minutes with such a huge load.

**Comment by machariamuguku** [comment]
This is helpful thanks @faith-mutua
