### ISSUE TITLE
Onadata returns a 404 (not found) when geojson is requested from a form with polylines or polygons only

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#2350]
### Environmental Information

- Onadata version: v3.7.1 (2022-12-22) [Latest](https://github.com/onaio/onadata/releases/latest)

### Problem description
For a form with polylines and polygons, the geojson endpoint returns a 404 not found 
### Expected behavior
The geojson endpoint should return the form's geojson

**Comment by faith-mutua** [comment]
@FrankApiyo this error is still recurring on stage.ona.io. When you load the map on [this form](https://stage.ona.io/faithm2/12/3805) the error `No data` is rendered on the page. The user `frankapiyo` has Can Edit access

**Comment by faith-mutua** [comment]
@FrankApiyo This issue has been resolved. Polygons and polylines are now being loaded on the Map Tab in beta mode for a form that only has the two geo files.

**Comment by faith-mutua** [comment]
@FrankApiyo This issue has now been resolved fully.
