### ISSUE TITLE
Multi-Language Form Exports: Handle `AttributeError` raised when exporting data with missing labels in a secondary language

### ISSUE THREAD

**Issue by DavisRayM** [onaio/onadata#2413]
### Environmental Information

- Onadata version: `main`

### Problem description

When exporting a form that's missing a label for one of the secondary languages the application returns a 500 with the unhandled exception: `AttributeError: 'NoneType' object has no attribute 'strip'`. I think this error can be handled better by either:

- Raising a warning during upload that some translations are missing. We can check translations present so far and warn that some translations are missing; This is more preventive
- Falling back to the default language if a label is missing
- Letting the export fail and giving an understandable explanation in the `failure_reason`

### Additional Information

See: https://onaio.slack.com/archives/C4S0D2S3H/p1682428938548639

**Comment by faith-mutua** [comment]
@kelvin-muchiri the exports are now falling back to the default language if a label is missing.
