### ISSUE TITLE
Noticed the following ONA Data API limitations:

### ISSUE THREAD

**Issue by machariamuguku** [onaio/onadata#2472]
Noticed the following ONA Data API limitations:
1. Some submissions don't have the `_date_modified` field. This is a challenge as that's the field we use as a cursor field
	- The workaround of using either the `_last_edited` or the `_submission_time` is patchy and creates loopholes
2. The API returns wrong records against logical filters
	- `?query={"_date_modified": {"$gt": "2023-07-18T19:09:52"}}` returns records with `_date_modified` matching the exact filter
	- `?query={"_date_modified": {"$gte": "2023-07-18T19:09:52"}}` has the same effect
3. The API does not support filtering using date fields with timezones
	- `&query={"_date_modified": {"$gt": "2023-07-05T16:56:32.172+02:00"}}`
	- we have to programmatically remove the timezone info even though it's gotten from the same API (from the cursor fields `_date_modified`, `_last_edited`, and `_submission_time`
4. The API does not return pagination information (the `links` header) when using sorting
	- `?page=1&page_size=2&sort={"_date_modified": 1}` this does not return links header
	- `?page=1&page_size=2` this does

_Originally posted by @machariamuguku in https://github.com/onaio/source-ona-data/issues/19#issuecomment-1702914169_

**Comment by ukanga** [comment]
@machariamuguku 
1. Why is the `_date_modified` relevant? The `_date_modified` historically was only added if a record had been edited. If it has not been edited then there is no reason the record should have `_date_modified`. Note: this does not mean the submission data was edited, just the DB record was modified in in most situations it may not touch the XML and JSON submission itself.
Why is the `_submission_time` patchy? Can you explain? this represents when on the server the record was received.
The `_last_edited` field when present does indicate that the XML/JSON submission has been modified and most likely edited either via Enketo or the CSV upload edit option.
How is the current implementation affecting integration with the understanding that this fields are and can be optional?
The Reasons we may not include them always are:
    1. Minimise the data size on the JSON column by including fields that are not necessary unless that activity has been noted.
    2. The presence of the field indicates a particular action occurred, we do not have to maintain a separate field for such activities.

**Comment by kelvin-muchiri** [comment]
@machariamuguku For number 2, it appears its working fine with only the caveat that `?query={"_date_modified": {"$gt": "2023-07-18T19:09:52"}}` will include the record whose `_date_modified` is `"2023-07-18T19:09:52"` unless you start from the next millisecond such `"2023-07-18T19:09:53"`

**Comment by ukanga** [comment]
The path to resolution:
1. Store the date and time in ISO format that includes the milliseconds and timezone time in the JSON field data for all date fields generated serverside. This is not the case at the moment.
2. The defect is not in how the logical filters are applied but in the data used since it is not complete as stored in the database where the milliseconds are excluded from the API data returned but are present in the data stored. 
3. Will be investigated and resolved
```JSON
{
  "detail": "invalid input syntax for type timestamp with time zone: \"2020-12-18T09:36:19.767455 00:00\"\nLINE 1: ...65119) AND deleted_at IS NULL AND date_modified > '2020-12-1...\n                                                             ^\n"
}
```
4. Will be investigated and resolved.

**Comment by kelvin-muchiri** [comment]
The `invalid input syntax for type.....` is being thrown because `+` in the URL is being parsed into a white space. The work around that can be applied at the moment is to encode it to `%2b` so `2023-07-05T16:56:32.172+02:00` becomes `2023-07-05T16:56:32.172%2b02:00`

Also the reason this was not in our tests is because the test cases testing this functionality use [APIRequestFactory](https://www.django-rest-framework.org/api-guide/testing/#apirequestfactory) instead of [APIClient](https://www.django-rest-framework.org/api-guide/testing/#apiclient). [APIClient mimicks the browser](https://stackoverflow.com/a/32137307/3247914). Using it have been able to replicate the bug in the test cases cc @ukanga @machariamuguku

**Comment by kelvin-muchiri** [comment]
@ukanga  Should we have the client amend the URL to encode the + or should we have the API apply fix to reformat the value as desired?

**Comment by okal** [comment]
I think the fix should be on the client side, but that the test cases should be updated. + to space is standard encoding. I think it could get really messy if we start adding exceptions to how those are interpreted.

**Comment by machariamuguku** [comment]
@kelvin-muchiri The API client I'm using encodes the request and it still returns the error:

This request: 
```bash
?query={"_date_modified": {"$gt": "2020-12-18T09:36:19.767455+00:00"}}&page_size=1
```
Is encoded to 
```bash
?query=%7B%22_date_modified%22%3A%20%7B%22%24gt%22%3A%20%222020-12-18T09%3A36%3A19.767455%2B00%3A00%22%7D%7D&page_size=1
```

But it still fails with: 
```bash
{
  "detail": "invalid input syntax for type timestamp with time zone: \"2020-12-18T09:36:19.767455 00:00\"\nLINE 1: ...65119) AND deleted_at IS NULL AND date_modified > '2020-12-1...\n                                                             ^\n"
}
```

Looks like a decoding error

**Comment by kelvin-muchiri** [comment]
@machariamuguku When I test on the browser without the encoding, I get the 400 error, I change URL with the encoding, I am getting a successful response

**Comment by machariamuguku** [comment]
@ukanga @kelvin-muchiri My bad, turns out the request is encoded properly (`%2B`) by the ETL connector client but is sent unencoded (`+`) by API clients (postman and thunder)

**Comment by kelvin-muchiri** [comment]
@okal @ukanga I think updating the tests will not change anything. I think what we should update is the documentation.

**Comment by kelvin-muchiri** [comment]
@ukanga The dates in [get_full_dict](onadata/apps/logger/tests/models/test_instance.py) (`_date_modified_`, `_submission_time`) are always 1 step behind the model's fields. 

`auto_now ` is updated when calling `Model.save`. That means line `[DATE_MODIFIED] = self.date_modified.strftime(MONGO_STRFTIME)` will always be assigned the previous value of `date_modified` during save while `date_modified` is now updated with the current time. 

Should we be updating the `json` inside a `post_save` signal instead?

**Comment by okal** [comment]
> @okal @ukanga I think updating the tests will not change anything. I think what we should update is the documentation.

Yeah, I think you have a point @kelvin-muchiri. It was an invalid input, and resulted in a meaningful error message to the client. I do wonder if there might be a better way to signal to clients what's going on. Might be something to talk through with @machariamuguku, to see if there might have been a way to make the issue more obvious to someone scanning the response.

**Comment by okal** [comment]
> @ukanga The dates in [get_full_dict](https://github.com/onaio/onadata/blob/main/onadata/apps/logger/models/instance.py#L531) (`_date_modified_`, `_submission_time`) are always 1 step behind the model's fields.
> 
> `auto_now ` and `auto_now_add` are updated when calling `Model.save`. That means line `[DATE_MODIFIED] = self.date_modified.strftime(MONGO_STRFTIME)` will always be assigned the previous value of `date_modified` during save while `date_modified` is now updated with the current time.
> 
> Therefore `Instance.json.get("_date_modified")` will always be referencing the previous `date_modified` value which is incorrect. I have manually tested this to verify
> 
> Should we be updating the `json` inside a `post_save` signal instead?

Hm. I think, in a perfect world, we shouldn't be tracking this info in two different places. Might the suggested approach result in auto_now being called yet again, since the json is a property of the model, which is being modified in its own post-save signal? And wouldn't that result in the same problem, and be a possible recipe for resource contention? Maybe instead of having auto_now on the date_modified field, the code could use the same explicitly set timestamp for both the field and the json (in an overridden save method, or something similar).

**Comment by kelvin-muchiri** [comment]
> Might the suggested approach result in auto_now being called yet again, since the json is a property of the model

Thanks @okal hadn't thought of this case, leads us back to square 1

**Comment by kelvin-muchiri** [comment]
@okal I agree, the other option would be to set them explicitly and remove reliance of `auto_now` and `auto_now_add`

**Comment by kelvin-muchiri** [comment]
But from what I see from the code alot is going on such as getting the attachments, notes e.t.c which are expensive operations which makes sense to perform them before hand

**Comment by kelvin-muchiri** [comment]
@ukanga Thanks, I think I might need to create a new issue for this and handle it in a separate issue?

**Comment by kelvin-muchiri** [comment]
@ukanga I have create a separate issue for here [Instance model date_modified and date_created fields are out of sync with their aliases in the json field](https://github.com/onaio/onadata/issues/2480)

**Comment by kelvin-muchiri** [comment]
After further analysis, it turned out that this issue and issue #2480 are mutually inclusive and have been handled by the same PR https://github.com/onaio/onadata/pull/2477
