### ISSUE TITLE
Filtering data by start value fails with 500 error

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#2536]
### Environmental Information

- Onadata version:

### Problem description

Filtering data from the data endpoint using a start value i.e. `/api/v1/data/<form-id>.?start=2` is failing with a `500 Internal Server` error

### Expected behavior

The submission record at the specified value should be returned

### Steps to reproduce the behavior

Filter data from the data endpoint using a start value i.e. `/api/v1/data/<form-id>.?start=2

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by ukanga** [comment]
@faith-mutua Are you still able to replicate this issue? The related sentry error no longer exists. I am only encountering 404, which is the expected behaviour.

**Comment by faith-mutua** [comment]
@ukanga I am now getting a `404` error
