### ISSUE TITLE
Images not exported to Google sheets connection

### ISSUE THREAD

**Issue by faith-mutua** [onaio/onadata#2546]
### Environmental Information

- Onadata version: 3.17.3

### Problem description

Syncing data with images to a live Google sheets connection doesn't sync over image links of the images collected alongside the data. Only the file names of the images are being synced

### Expected behavior

Image links for images collected alongside survey data should also be synced to the live Google Sheets connection

### Steps to reproduce the behavior

1. Submit some data to this test form [Colourful_Choices.xlsx](https://github.com/onaio/onadata/files/14065005/Colourful_Choices.xlsx)
2. Connect the form to Google Sheets
3. Observe that image links are not synced to Google Sheets

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by faith-mutua** [comment]
@kelvin-muchiri I have observed the following when testing the fix
1. A broken link is created for the Images exported to the created Google Sheets connection. The link has a `http` method instead of `https`. Adding the missing `s` to the HTTP method downloads the image. The broken link is also being included in other data exports
2. Records uploaded to a form via Import CSV have the image link added to the image column even though the image wasn't uploaded alongside the data. This is also happening in other data exports

**Comment by FrankApiyo** [comment]
This is a configuration issue. There's a specific config that can fix this on the API

**Comment by faith-mutua** [comment]
@kelvin-muchiri the issue with the broken link has been resolved. The correct image link is synced to Google sheets and clicking on it downloads the attached image as expected. 

On issue #2, it is working as expected and happens for data imports that had the image link exported together with the data.

This issue is now resolved.

**Comment by FrankApiyo** [comment]
@faith-mutua please go ahead and close this if it's resolved
