### ISSUE TITLE
Child questions of grouped sections within repeating sections not ignored during CSV export 

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2562]
### Environmental Information

- Onadata version: v3.18.1

### Problem description

During a CSV export, if a question is a child of a grouped section that is a child of a repeating section, the question is not ignored during the export and the question is included in the CSV header columns.

### Expected behavior

The question should be ignored from the CSV header columns as the question is already present as part of the indexed column headers

### Steps to reproduce the behavior

1. Make submissions to an XLSForm that has grouped section inside a repeating section. Here is an example 
[multiples-group-repeat.xlsx](https://github.com/onaio/onadata/files/14384836/multiples-group-repeat.xlsx)
2. Export the CSV data without splitting select multiples. Check the header columns will match the following `name, age, grp1/grp2/browser_use[1]/grp3/grp4/grp5/year, grp1/grp2/browser_use[1]/grp3/grp4/grp5/browsers, grp1/grp2/browser_use[2]/grp3/grp4/grp5/year, grp1/grp2/browser_use[2]/grp3/grp4/grp5/browsers, grp1/grp2/browser_use/grp3/grp4/grp5/year, grp1/grp2/browser_use/grp3/grp4/grp5/browsers...`
3. The correct header columns should be `name, age, grp1/grp2/browser_use[1]/grp3/grp4/grp5/year, grp1/grp2/browser_use[1]/grp3/grp4/grp5/browsers, grp1/grp2/browser_use[2]/grp3/grp4/grp5/year, grp1/grp2/browser_use[2]/grp3/grp4/grp5/browsers...`
4. Now export the CSV data with split select multiples. The out come should be similar where the non-indexed repeat question columns are included 

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by faith-mutua** [comment]
@kelvin-muchiri the issue has been resolved on stage.ona.io
