### ISSUE TITLE
Allow unauthenticated requests to submission viewset

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#2568]
### Problem description
With Require Phone Authentication enabled, the endpoint Enketo uses to get max attachment size (https://odk.ona.io/enketo/<form-id>/submission ) returns 401s but when disabled the endpoint returns 200 response codes
### Expected behavior
HEAD requests to `/<user>/<form-id>/submission` endpoint should return a success response code

**Comment by ukanga** [comment]
@FrankApiyo Are we ignoring the authentication digest from Enketo, or is it not sent at all? If it is the latter, should Enketo send an authentication digest?
The endpoint is behaving as expected.

**Comment by FrankApiyo** [comment]
Enketo [sends authentication headers](https://github.com/enketo/enketo/blob/main/packages/enketo-express/app/lib/communicator.js#L124) but it seems to fail consistently for this particular `HEAD` request. I made [some recommendations](https://github.com/onaio/onadata/pull/2565) for changes we might make on our end
