### ISSUE TITLE
Permissions for a merged dataset not applied when a project is shared with user

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2596]
### Environmental Information

- Onadata version: v4.1.0

### Problem description

When a merged dataset is created, the permissions are applied correctly for existing users on the project. However, when a new user is added to the project or organization, the permissions are not applied, and the user gets a 404 when they access the dataset.

### Expected behavior

A user with the appropriate permissions should view a merged dataset if the user was added **after** the merged dataset was created

### Steps to reproduce the behavior

1. [Create a merged dataset](https://github.com/onaio/onadata/blob/main/docs/merged-datasets.rst#create-a-new-merged-dataset)
2. Add a user to the project or organization with the appropriate permissions to view a merged dataset.
3. Login as the user or request the user to [access](https://github.com/onaio/onadata/blob/main/docs/merged-datasets.rst#retrieve-a-merged-dataset) the dataset. They will get a 404 response.
4. Create a new merged dataset under the same project. The user can now access the latest merged dataset and will get a 200 response.

### Additional Information

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by faith-mutua** [comment]
@kelvin-muchiri this issue has been resolved. Users can now view merged datasets when they are added to a project after the merged dataset was created.
