### ISSUE TITLE
Export deletion fails with error

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2601]
### Environmental Information

- Onadata version: v4.1.0

### Problem description

When deleting an export, the export fails with a status code of 500

### Expected behavior

The export should be successful with a HTTP status code of 204

### Steps to reproduce the behavior

1. [Create a data export](https://github.com/onaio/onadata/blob/main/docs/forms.rst#export-form-data-asynchronously)
2. Delete the data export via endpoint `DELETE /api/v1/exports/<pk>`

### Additional Information

The exception thrown is captured below
![Screenshot from 2024-05-20 13-54-09](https://github.com/onaio/onadata/assets/19818819/55f7c562-b836-43aa-a46a-cae9f1f48c08)

**Comment by faith-mutua** [comment]
@kelvin-muchiri this is now resolved. I have managed to delete exports
