### ISSUE TITLE
Integer and decimal 0 values rendered as literal strings on data endpoint

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2619]
### Environmental Information

- Onadata version: <= 4.2.2

### Problem description

A submission's integer and decimal type of questions have their 0 values returned as literal strings i.e `'0'` and `'0.0'` respectively on the endpoint `/api/v1/data/<form_id>` when the response format is JSON

### Expected behavior

0 values for integer and decimal should be returned as literal integers and decimals respectively when returning the response in JSON format on endpoint `api/v1/data/<form_id>`

### Steps to reproduce the behavior

1. Upload a form with integer and decimal type of questions.
2. Make submission with values for the fields 0
3. Visit the endpoint `/api/v1/data/<form_id>`. You will find the values for the integer field is `'0'` and that for the decimal field is `'0.0'`

**Comment by faith-mutua** [comment]
@kelvin-muchiri this is now resolved on stage-api.ona.io

![Screenshot from 2024-06-26 14-46-04](https://github.com/onaio/onadata/assets/17847885/7f0f1755-d69b-47f8-95f5-05988cbaa6b5)
