### ISSUE TITLE
Entity related data missing in project retrieve endpoint 

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2638]
### Environmental Information

- Onadata version: <= v4.3.2

### Problem description

The endpoint `/api/v1/projects` contains keys `contributes_entities_to` and `consumes_entities_from` for each form item. The keys are missing in endpoint `api/v1/projects/<id>` and should be added.

### Expected behavior

The `form` list items on endpoint `api/v1/projects/<id>` should have the `contributes_entities_to`,  `consumes_entities_from` keys

### Steps to reproduce the behavior

Visit the endpoint `api/v1/projects`. Each form item has a `contributes_entities_to` and `consumes_entities_from`
Now visit `api/v1/projects/<id>`. Each form item does not have `contributes_entities_to` and `consumes_entities_from` keys.

**Comment by faith-mutua** [comment]
@kelvin-muchiri this has now been resolved

![Screenshot from 2024-07-08 16-02-35](https://github.com/onaio/onadata/assets/17847885/f21ed92c-c568-4fd3-9eee-ddd2b65bc40c)
