### ISSUE TITLE
Stale data sent to rest services after editing a submission

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2668]
### Environmental Information

- Onadata version: <= 4.4.0

### Problem description

After editing a submission, sometimes the data sent to rest services is the old data just before the edit was made.

### Expected behavior

After editing a submission, the data sent to rest services should at all  times be the latest data.

### Steps to reproduce the behavior

Reproducing the bug can be challenging since it is intermittent. To try and reproduce the bug, connect the form to some external service such as RapidPro. Make a submission, then edit the submission. The data received on the external service may be stale.

### Additional Information

This [line](https://github.com/onaio/onadata/blob/main/onadata/libs/utils/logger_tools.py#L184) is responsible for calling the signal that calls the rest services' webhooks. The second argument `instance`, is assumed to be used as it is since it's properties have been updated with the latest data. However, the `Instance` is later retrieved afresh from the database both when handing the call [synchronously](https://github.com/onaio/onadata/blob/main/onadata/apps/restservice/signals.py#L31) or [asynchronously](https://github.com/onaio/onadata/blob/main/onadata/apps/restservice/signals.py#L27). It is not guaranteed that the submission will have been saved to the database by this time.

The issue had been identified and [resolved](https://github.com/onaio/onadata/pull/2522) earlier. However, there was an oversight during the fix, as it was not considered that when calling the webhooks, it isn't guaranteed that the `Instance` would have been saved to the database.  `Instance.xml` could refer to the old value instead of the new one.

**Comment by karina4050** [comment]
@kelvin-muchiri 
This here has been resolved and thus passed QA. User gets an email when:
1. A new submission is made
2. After reviewing a submission via the enketo form with either an approved, completed or rejected status.
