### ISSUE TITLE
Account activation email sent after creating organization

### ISSUE THREAD

**Issue by kelvin-muchiri** [onaio/onadata#2669]
### Environmental Information

- Onadata version: <= 4.4.0

### Problem description

After creating an organization, an account activation email is sent to the email specified when creating the organization. The following is an example of the email sent:

_You (or someone pretending to be you) have asked to register an account at ."
Also note that the provided link does not work; it seems to be missing domain information:
[start]
To activate this account, please click the following link within the next 1 days:
[/accounts/activate/cac3309a5480364caabb66c2d95f731f194b609f8ff2ec2287e1cfbf6b3f6197/](http://accounts/activate/cac3309a5480364caabb66c2d95f731f194b609f8ff2ec2287e1cfbf6b3f6197/)_

### Expected behavior

No activation email should be sent upon creating an organization

### Steps to reproduce the behavior

1. [Create an organization](https://github.com/onaio/onadata/blob/main/docs/orgs.rst#register-a-new-organization)
2. Check the inbox for the email you used when registering the organization. You should receive an activation email similar to  the one above.

### Additional Information

This is the [piece of logic](https://github.com/onaio/onadata/blob/main/onadata/apps/api/tools.py#L183) triggering the sending of the activation email. The activation email was not being sent before this [change](https://github.com/onaio/onadata/pull/2647) because the email was always empty, hence the bug had never occurred before the change.

**Comment by faith-mutua** [comment]
@kelvin-muchiri this now addressed on stage.ona.io. I have not received an activation email upon creating an organization account
