### ISSUE TITLE
Move API docs out of code and into a separate app or tool

### ISSUE THREAD

**Issue by pld** [onaio/onadata#292]
* could be sphinx
* could involve involving RAML

**Comment by sichvoge** [comment]
Hi @pld - where are you with both? Just browsed github looking for Sphinx and RAML and found your project. ;)

**Comment by pld** [comment]
Hi @sichvoge! We ended up using Sphinx for this, we've used it before so it was simpler for us to setup.

**Comment by sichvoge** [comment]
OK - cool. Thanks @pld
