### ISSUE TITLE
Make media API more consumer friendly

### ISSUE THREAD

**Issue by prabhasp** [onaio/onadata#559]
- [x] Add an endpoint:
  `https://stage.ona.io/api/v1/media.jpg?filename=ATTACHMENT_NAME&instance=DATA_ID` (eg. `https://stage.ona.io/api/v1/media.jpg?filename=123345.jpg&instance=2455`
  This should be a link directly to the image, as opposed to data about the image.
- [x] Add media information as an `_attachments` element to each submission data. The associated value should be exactly the object returned if we were to query
  `https://stage.ona.io/api/v1/media.jpg?instance=DATA_ID` for that record / instance.
- [x] All media objects should have an additional field, called `field_xpath`, which stores the `name` of the question from the xform. See discussion on the Project Zebra mailing list for rationale. The term `field_xpath` taken from the chart API output.
- [x] Add links to small and medium thumbnails.

Aha! Link: https://ona.aha.io/features/PROD-816

**Comment by neilp9** [comment]
@prabhasp , this is a useful API! Would would be great (and probably quite simple), is if it could accept multiple instance IDs in the query. This is useful for paginating data table: I don't want all the data from a form (?xform=XXX), and I don't want to have to query for each instance on the page separately (?instance=XXX). So if I could do /media?instance=X&instance=Y..., I could efficiently refresh pages
