### ISSUE TITLE
GPS coordinate 0 0 doesn't appear on maps.

### ISSUE THREAD

**Issue by hodgestar** [onaio/onadata#661]
If we upload a location of "0 0" or "0.0 0.0" it doesn't appear on the map even though this is a valid GPS coordinate. It's a location in the Gulf of Guinea about 625 km south of Tema, Ghana, so it's probably not that likely to be used unless Ona starts including ships. We didn't check "0 X" or "Y 0" though -- it's possible those are affected too.

**Comment by hodgestar** [comment]
Is there another format GPS co-ordinates can be submitted as? I seem to
recall we tried a JSON list but that that didn't work.

For the record, we are successfully submitting string co-ordinates
currently without the accuracy and elevation.

**Comment by DavisRayM** [comment]
Closing this for now, please reopen this if this is needed.
