### ISSUE TITLE
ODK Collect section on getting started page needs update

### ISSUE THREAD

**Issue by nathanathan** [onaio/onadata#772]
The ODK Collect setup instructions on the getting started page (https://ona.io/getting_started/#use-odk-collect) are not very helpful compared to the instructions at http://help.ona.io/faq/odk-collect/ . However, when searching for instructions for using ODK Collect with ona.io, the getting started guide was the first result I found on Google. I recommend removing the ODK Collect instructions on the getting started page so they don't prevent people from finding the better instructions and linking to the FAQ page instead.

**Comment by DavisRayM** [comment]
Closing this for now, please reopen this if this is needed.
