### ISSUE TITLE
Submissions and formList requests fail if auth provided when account does not require this.

### ISSUE THREAD

**Issue by MartijnR** [onaio/onadata#780]
I think I finally figured out why requests to /formList and submissions started failing on ona.io (only) in the last week or so.

https://github.com/kobotoolbox/enketo-express/issues/248
https://github.com/kobotoolbox/enketo-express/issues/257

The /formList failure results in this empty XML document:

``` xml
<xforms xmlns="http://openrosa.org/xforms/xformsList"></xforms>
```

It seems to be caused by sending account credentials (Basic or Digest, whatever ona.io requires) when the account does not (no longer) have the 'Requires Phone Authentication' setting enabled.

The desired behaviour would be to ignore credentials when they are sent (though Enketo shouldn't actually send them if a HEAD request does not respond with 401).

**Comment by MartijnR** [comment]
Sorry cannot reproduce this any more now. It may not be the cause of receiving an empty formList.

**Comment by MartijnR** [comment]
Whatever the actual cause for the empty formlist the solution is to clear the cookie by going to yourenketo-express.com/logout.

**Comment by MartijnR** [comment]
I think this issue will only occur if you use both OpenRosa authentication (or have in the past) and your own authentication with Enketo. So probably not a big deal. Still a bug but only noticeable by some Enketo developers ;).

**Comment by DavisRayM** [comment]
CC: @ukanga @ivermac @lincmba @WinnyTroy

**Comment by DavisRayM** [comment]
This doesn't seem like an issue any more. Closing it for now, please reopen if it's need once again.
