### ISSUE TITLE
S3 Setup

### ISSUE THREAD

**Issue by hallahan** [onaio/onadata#786]
Instead of saving media attachments on the local filesystem, we might want to configure items to be saved to S3. We need instructions on how to set this up.

**Comment by dalekunce** [comment]
Formhub has the following settings which I hope we can still use. No documentation exist for s3 or SES settings 

```bash
# These are necessary for running on Amazon Web Services (AWS)
# because basic formhub/django functions which rely on email,
# such as new account registration, will fail

AWS_ACCESS_KEY_ID     = '<secret key>' # find these in your AWS console
AWS_SECRET_ACCESS_KEY = '<access key>'
EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = '<email address>' # e.g., 'no-reply@example.com'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment the following three lines if you are using
# an AWS S3 Bucket as the default file store, and define
# your bucket name in the AWS_STORAGE_BUCKET_NAME variable.
# This it is optional, but strongly recommended.

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
AWS_STORAGE_BUCKET_NAME = '<bucket name>' # use your S3 Bucket name here
AWS_DEFAULT_ACL = 'private'
```

**Comment by mberg** [comment]
I don't think it's changed hence the reason we don't have docs for this

**Comment by dalekunce** [comment]
@mberg anything other special besides running

```bash
pip install -r requirements-s3.pip
```

**Comment by mberg** [comment]
Copying in @ukanga who can confirm

**Comment by dalekunce** [comment]
@mberg @ukanga is there an easy way to test if this is setup correctly. Can't test until the SES issue #785 is resolved as I can't activate any accounts.

**Comment by mberg** [comment]
It's night in Kenya so might take until tomorrow to respond.  You can
activate users via the djanfo admin accessible at /admin if you are logged
in as the super user

**Comment by dalekunce** [comment]
ok so I found and ran pip install -r /home/ubuntu/onodata/requirements s3.pip

how do I setup the superuser, same old formhub way?

python manage.py createsuperuser

**Comment by dalekunce** [comment]
I ran 

```bash
pip install -R s3.pip 
```
Updated my s3 credentials in local_settings.py

Uploaded a form and received an error.

<img width="687" alt="screen shot 2015-08-12 at 3 56 10 pm" src="https://cloud.githubusercontent.com/assets/1913857/9238869/d9576eba-410a-11e5-8217-c5b01b3bc422.png">

**Comment by dalekunce** [comment]
ok got s3 working by running

```bash
source ~/.virtualenvs/onadata/bin/activate
pip install -r onadata/requirements/s3.pip --allow-all-external
```

**Comment by mberg** [comment]
Ok good to know.  Let us know if you have any other issues and i'll have
our team in Nairobi respond in the AM

---------- Forwarded message ----------

**Comment by DavisRayM** [comment]
Closing this for now, please reopen this if this is needed.
