### ISSUE TITLE
403 Cross domain stuff

### ISSUE THREAD

**Issue by dalekunce** [onaio/onadata#789]
activated a user using the SuperUser interface. Tried to login and got the following.

<img width="1127" alt="screen shot 2015-08-11 at 1 08 08 pm" src="https://cloud.githubusercontent.com/assets/1913857/9209268/6bbf4070-402a-11e5-81f1-6f65ea34c0de.png">

**Comment by dalekunce** [comment]
@mberg any progress on this error. Its keeping us from deploying OMK for a field project in South Africa.

**Comment by mberg** [comment]
Dale - can you explain a bit more what you are trying to do and where you
are getting this error?  How far along you've come in setting things up.

@ukanga @pld do you know what's happening here?

Dale - really happy to help make sure things are running smoothly for you.
We don't have any context of what you need help getting setup, by when,
etc.

**Comment by dalekunce** [comment]
just trying to get it turned on with s3 and ses support.

**Comment by dalekunce** [comment]
figured it out. I ran the following command yesterday that corrupted the database. Restarted with a refresh AMI didn't run the command and am able to login. Albeit without an email link.

```bash
python manage createsuperuser
```
