### ISSUE TITLE
unable to checkout osm

### ISSUE THREAD

**Issue by neilp9** [onaio/onadata#790]
On a vanilla dev instance, following the install guide, I get:

root@li850-97:/home/ona# git clone https://github.com/onaio/onadata.git onadata
Cloning into 'onadata'...
remote: Counting objects: 53797, done.
remote: Total 53797 (delta 0), reused 0 (delta 0), pack-reused 53797
Receiving objects: 100% (53797/53797), 21.36 MiB | 5.79 MiB/s, done.
Resolving deltas: 100% (37941/37941), done.
Checking connectivity... done.
root@li850-97:/home/ona# cd onadata/
root@li850-97:/home/ona/onadata# git checkout osm
error: pathspec 'osm' did not match any file(s) known to git.

**Comment by mberg** [comment]
I think that's been merged to master.  @ukanga can you confirm?

**Comment by neilp9** [comment]
that would make sense. There is no branch with that name. Have submitted a pull request

**Comment by pld** [comment]
I can confirm it had been merged
