### ISSUE TITLE
Use ENKETO_PROTOCOL universally

### ISSUE THREAD

**Issue by neilp9** [onaio/onadata#793]
Ona currently assumes enketo will be able to access the forms server with SSL (https). See [this thread](https://groups.google.com/forum/#!searchin/enketo-users/ona/enketo-users/6ecRelpE3QU/VNoS3ISjCQAJ) for a discussion. Instead, it would be great if Ona doesn't assume SSL for generating form URLs. There is already a setting `ENKETO_PROTOCOL` that is [used in some places](https://github.com/onaio/onadata/search?utf8=%E2%9C%93&q=_get_form_url). It would be great if this is used universally.

**Comment by DavisRayM** [comment]
This has been introduced. Closing this issue, please comment if you need more information on this feature.
