### ISSUE TITLE
correctly generate Enketo preview URL from API

### ISSUE THREAD

**Issue by neilp9** [onaio/onadata#795]
Enketo preview URLs are being generated [here](https://github.com/onaio/onadata/blob/6ff4011a66e7df1c9f9cf3e2e158b66584980964/onadata/apps/main/views.py#L1329). This is incorrect, see this [discussion](https://groups.google.com/forum/#!topic/enketo-users/t_F2J2n3PC0). Ona needs to get the preview URL from the Enketo API, `POST`ing to `survey/preview`

**Comment by DavisRayM** [comment]
We now generate the enketo preview urls by making posts to the endpoint. This should no longer be an issue.

Closing this for now, please reopen if necessary.
