### ISSUE TITLE
Adding media (photo, audio, video) in enketo forms not working

### ISSUE THREAD

**Issue by biosmooth** [onaio/onadata#796]
I used the exemplary form with the local onadata installation combined with local installation of enketo-express, 
 * [Birds](https://docs.google.com/spreadsheets/d/1Rxft3H3xl3M9bLFGR2XhXzt1ucyFmd0qFmOQ6FaqJw4/edit#gid=246559171) 
 * e.g. accessible [here](https://l2sje.enketo.org/webform)

Photo upload (google chrome on Debian) to media question entitled "If possible, please take a picture of your observation"  does not work. There is no message at all after uploading the photo in the browser ( not image preview which is expected). However following error appears in chrome webdev tools:
 * Uncaught ReferenceError: _isTooLarge is not defined (enketo-webfrom-bunde.min.js:11)
![enketo_error_image_upload](https://cloud.githubusercontent.com/assets/576450/10131526/3cde12b4-65d1-11e5-9d69-ee70942ab1c9.png)

**Comment by MartijnR** [comment]
now fixed in 1.19.3 (kobotoolbox/enketo-express)

**Comment by pld** [comment]
:+1:
