### ISSUE TITLE
Form version list in export data is unordered

### ISSUE THREAD

**Issue by bcardiff** [onaio/onadata#797]
<img width="572" alt="screen shot 2015-09-30 at 2 23 31 am" src="https://cloud.githubusercontent.com/assets/459923/10185121/003edbea-671b-11e5-8104-db1ea1888ce6.png">

There is no direct way to export one or a selected subsets of records to json. I recall it was there in the past and it was useful to troubleshoot integration of rest services.

**Comment by DavisRayM** [comment]
@FrankApiyo Please check if this is still an issue.
