### ISSUE TITLE
metadata "username" not populated

### ISSUE THREAD

**Issue by MartijnR** [onaio/onadata#801]
This is a consequence of using 'external authentication' that I hadn't thought of before. Not sure if it belongs in this repo but I think so. Enketo express would have no knowledge of the username if external authentication is used.

A solution would be to set/maintain an `__enketo_meta_uid` cookie. See code here that populates this value in the form: https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L1477-L1478

**Comment by pld** [comment]
Thanks Martijn, this will be closed by the next batch update the onadata
code

**Comment by DavisRayM** [comment]
This feature already exists. Closing this for now, please reopen if more information is needed on this.
