### ISSUE TITLE
hyperlink to media sometimes missing in table view

### ISSUE THREAD

**Issue by MartijnR** [onaio/onadata#802]
I used [this form](https://docs.google.com/spreadsheets/d/1xsASRcfsXvV6B43Hx8mojzg89ucp45ThEwB29QtWBrE/edit#gid=0) with **the latest** (emphasized, because until yesterday EE had some bugs with submitting media in the offline-capable views) Enketo Express and https://ona.io.

The issue is that the hyperlinks to media are sometimes not created. See below:

<img width="412" alt="screen shot 2015-12-08 at 2 43 45 pm" src="https://cloud.githubusercontent.com/assets/627350/11669511/570a9196-9dba-11e5-9cfd-6596ea253e61.png">

The media files do actually exist (verified when exporting media files as zip).

**Comment by overnin** [comment]
@MartijnR my enketo-express (v1.9.2) is not able to load the pictures from my ONA instance (See screenshot below). However the pictures are available in the ONA http://<mydomain.com>/media/<username>/attachments/1462276052732.jpg

<img width="1135" alt="screen shot 2016-05-17 at 20 31 05" src="https://cloud.githubusercontent.com/assets/896138/15334621/53c7a724-1c6f-11e6-9d34-3168f0b8656f.png">

My question is then how should ONA behave to work with Enketo? 
- Is there a missing fields in the submission xml?
- or is it another API call?

**Comment by MartijnR** [comment]
It's a missing feature: https://github.com/kobotoolbox/enketo-express/issues/50

**Comment by overnin** [comment]
@MartijnR that's right, thanks for point at the feature.

**Comment by DavisRayM** [comment]
We believe this is no longer an issue. Closing this for now, please reopen if it is.
