### ISSUE TITLE
Password validation should be enforced while changing an email

### ISSUE THREAD

**Issue by skambo** [onaio/onadata#812]
**Environment**
Preview/Chrome

**To reproduce**
- Enter an incorrect password so as to change your email 
- The email changes regardless of entering an incorrect password

**Expected result**
- Password should be correct before an email is changed.

**Comment by skambo** [comment]
@denniswambua @pld The incorrect password you enter when updating the email address won't work if you try log in with it.

**Comment by pld** [comment]
Well that's good
