### ISSUE TITLE
Create a json Web Data Connector(WDC) for Tableau

### ISSUE THREAD

**Issue by denniswambua** [onaio/onadata#817]
A Tableau Web Data Connector will help pulling data from Ona into Tableau for analysis and visualizations.
Use the links below to guide on how the Tableau Web Data Connector is created and hosted.
- Tableau Web Data Connector [Resources](https://community.tableau.com/message/394436#394436)
- Tableau Web Data Connector [Github](https://github.com/tableau/webdataconnector)
- Tableau Web Data Connector [Blog Post](https://www.tableau.com/about/blog/2016/2/wdc-now-open-source-and-taking-contributions-50142)

You can use Tableau Public for testing [here](https://public.tableau.com/s/download) , **Windows and Mac**

**Comment by denniswambua** [comment]
Pull this to another repo

**Comment by pld** [comment]
repo here: https://github.com/onaio/ona-tableau-connector
