### ISSUE TITLE
Allow readonly users to edit saved chart titles.

### ISSUE THREAD

**Issue by urbanslug** [onaio/onadata#831]
We want to fix an error on the widgets endpoint that forbids readonly users from editing saved chart metadata, since they are already able to save charts they should be able to edit the saved chart metadata.

**Comment by skambo** [comment]
@urbanslug pls include a fix for the 'can submit' users

**Comment by urbanslug** [comment]
After speaking to @ukanga I will come back to this later. We may need to add `CAN_EDIT/DELETE/ADD_WIDGET` permissions because as currently is, we don't have a proper way to check for widget objects. We are checking the project permissions which is wrong if not confusing.

@ukanga do you agree?

**Comment by pld** [comment]
@urbanslug I don't agree, why does this involved adding more permissions? The assumption is that this is about adjusting the existing permissions for an existing role, the readonly users role

**Comment by urbanslug** [comment]
@pld The way readonly users are able to create charts is in error. It basically allows anyone to create a chart.

**Comment by pld** [comment]
OK, but that doesn't imply that the fix is to add new permissions versus
having the existing permissions apply to the charts endpoint.
