### ISSUE TITLE
Exporting data with labels and without prefixed group names gets the name/variable columns mixed up

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#836]
This has been observed when you have an XLS export that has split choices into multiple columns, labels are included in the export and the group name has been resolved.

**Comment by ukanga** [comment]
Investigating this issue I found that the main culprit was `XForm.get_survey_element(name_or_xpath)` which seems to search by name even when xpath has been provided. This is a problem here because you are likely to have choices with the same name and since the first element matching the name is returned, you are likely to have an unexpected element.

**Comment by bmalina** [comment]
@skambo @ukanga tests complete and were successful. The columns have the correct names when exporting without the group names and the labels included.
