### ISSUE TITLE
Add a check for whether an account username is for an org account or personal account

### ISSUE THREAD

**Issue by KipSigei** [onaio/onadata#843]
At the moment any username/account can be added as a member of an org, regardless of whether it is an org too or a personal account.

A user can add an org account as a member of another org which shouldn't be the case. The check will assist in verifying whether a particular username belongs to an org or personal a/c before adding as a member of an org.

**Comment by pld** [comment]
@KipSigei where would this check go?

**Comment by KipSigei** [comment]
To the orgs endpoint

**Comment by pld** [comment]
Which one? You need to provide more details, what API requests would this affect, what API docs are related to this

**Comment by KipSigei** [comment]
https://api.ona.io/static/docs/orgs.html#add-a-user-to-an-organization
