### ISSUE TITLE
Update header to new Ona logo

### ISSUE THREAD

**Issue by mberg** [onaio/onadata#844]
Ideally a bit of other light redesign too to make this a bit more attractive.

<img width="1043" alt="screen shot 2016-11-18 at 12 52 09 pm" src="https://cloud.githubusercontent.com/assets/57921/20425945/fdef3b0e-ad8d-11e6-9974-79a84d297689.png">

**Comment by mberg** [comment]
Like remove the header links which aren't needed.

**Comment by jmunene** [comment]
Moved this issue to the Tableau Connector Repo
https://github.com/onaio/ona-tableau-connector/issues/3
closing this issue now
