### ISSUE TITLE
Form ownership transfer does not result to an update in enketo

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#845]
@cagulas and myself just discovered a bug - I don't think we ever thought about it initially when forms transfer was introduced. When a user transfers form ownership to another user/org, enketo is not updated to reflect the new owner or the new formList. This is a problem especially if the original url is already being used. I guess this is also a chance for someone else, other than me, to checkout and explore if this possible via the enekto API and how onadata will be able to do this

**Comment by DavisRayM** [comment]
This doesn't seem like an issue any more. Closing it for now, please reopen if it's need once again.
