### ISSUE TITLE
Add the ability to upload XML XForms to the /api/forms endpoint

### ISSUE THREAD

**Issue by pld** [onaio/onadata#848]
Modify the `/api/forms` endpoint to add the ability to accept XML XForms and create datasets from them.

Following the current pattern, https://api.ona.io/static/docs/forms.html#upload-xlsform, @ukanga suggests we add the parameter `xml_xform`.

Apparently this can be done via briefcase so this is a matter of refactoring and exposing the code that does that.

Docs need to be updated to reflect the new endpoint.

**Comment by ukanga** [comment]
I think adding `xform_xml` or something similar that you can `POST` on `/api/forms` endpoint would be the appropriate action here.

**Comment by pld** [comment]
Agreed, updated the title and description.
