### ISSUE TITLE
Add info to show form was published by formbuilder

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#876]
This info should be used by zebra to know if it should add a formbuilder edit link for a form or not. At the moment, it only makes sense to have edit links for forms that were published/deployed by the formbuilder.

**Comment by pld** [comment]
I do not think this is the type of attribute that deserves a database column of it's own. What other approaches are there?

**Comment by ivermac** [comment]
@pld I'm not suggesting adding an database column, just xform info that would let zebra know a form was deployed by the formbuilder. Check out [this PR](https://github.com/onaio/onadata/pull/877/files).

**Comment by pld** [comment]
OK, got it, cool.
