### ISSUE TITLE
Allow users with view permission to be able to preview a form

### ISSUE THREAD

**Issue by ivermac** [onaio/onadata#918]
Users with `can view` and `can view and download` permissions cannot access webforms - they do not have permissions to xforms shared with them. I had a discussion with @ukanga and he has suggested the following - @ukanga please correctly where I go wrong:
1. Add a custom permission class similar to [this one](https://github.com/onaio/onadata/blob/master/onadata/apps/api/permissions.py#L48) with `GET` having the report permission and `POST` having view permission. This class should then be inherited by the preview formlist class.
2. Have different `downloadUrl` and `manifestUrl ` for [preview formlist](https://github.com/onaio/onadata/blob/master/onadata/apps/api/viewsets/xform_list_viewset.py#L152). This will involve:
    - Having a new serializer class for preview formLIist. In my opinion, the new serializer should inherit from [this class](https://github.com/onaio/onadata/blob/master/onadata/libs/serializers/xform_serializer.py#L297) and the `downloadUrl` and `manifestUrl` should then be overridden.

**Comment by skambo** [comment]
Helpscout issue https://secure.helpscout.net/conversation/318498713/6397/?folderId=488731

**Comment by ukanga** [comment]
I think the best approach is the second one, have specific URLs preview xform and manifest files with `view_xform` role. The first approach will make available the `formList` to users who have no submit permissions.

**Comment by skambo** [comment]
On Firefox, with admin rights, if you open the webform, it redirects back to the homepage as well. (admin level rights open the webform on Chrome though)

**Comment by denniswambua** [comment]
Is this a functionality we want. Currently only `can submit` and above are able to preview the form. We should not enable `can view` to preview the form.

**Comment by ukanga** [comment]
Please reopen if it fails, seems to be working now.
