### ISSUE TITLE
XForm submission count goes out of sync.

### ISSUE THREAD

**Issue by urbanslug** [onaio/onadata#930]
When more than 1 submission is made in a short amount of time, the function https://github.com/onaio/onadata/blob/6ba53eeef174704b1bba76249c681e7a8959ced7/onadata/apps/logger/models/instance.py#L132  might save an incorrect number of submissions because a race condition may occur where different servers are handling different submissions for the same form therefore causing the function to calculate and save `submission_count` before all submissions have been made. This means the `submission_count` field in the xform will have an incorrect number, less than the actual submission count. Therefore making it go out of sync with the actual submission count.

Possible solutions:
1. Running python shell in production and calling https://github.com/onaio/onadata/blob/master/onadata/apps/logger/models/xform.py#L820 with `force_update=True` for the specific form that is out of sync.

2. Write a job to run every x time that calls https://github.com/onaio/onadata/blob/master/onadata/apps/logger/models/xform.py#L820 with `force_update=True` for every form that recieved a submission in the last x time

**Comment by pld** [comment]
How did you verify that this is happening? That function is annotated as an atomic transaction, doesn't that avoid this? The DB operations on the cell should be locked while another operation based on this function is running.

**Comment by urbanslug** [comment]
@pld Will close this until I have a better grasp of things here.
