### ISSUE TITLE
ubuntu 16.04 LTS install script

### ISSUE THREAD

**Issue by KaruguDev** [onaio/onadata#944]
only two changes are required
**sudo apt-get install -y postgresql-9.4-postgis-2.1 ~> sudo apt-get install -y postgresql-9.5-postgis-2.1
openjdk-7-jre ~> openjdk-8-jre**

**Comment by pld** [comment]
Cool, thanks @paul-100! Let's get these into the docs as a PR

**Comment by dev3320770** [comment]
@paul-100  did you manage to get the onadata installation to work

**Comment by mwaigichuhi** [comment]
This ona setup is really hard to achieve first time of asking. The docs really need to be improved without making assumptions (be verbose) on the target users.

I am not a python dev but should not struggle to setup ona as I have so here's some tested install steps:

#Ubuntu (14.04 only, I had no success with 16.04) Requirements

#RAM 1GB (minimum) avoids Memory error when installing one of the requirements

#Assuming non-root user with sudo privileges

sudo apt-get install git

git clone https://github.com/onaio/onadata.git

cd onadata

sudo ./script/install/ubuntu

sudo su postgres -c "psql -c \"CREATE USER onadata WITH PASSWORD 'onadata';\""
sudo su postgres -c "psql -c \"CREATE DATABASE onadata OWNER onadata;\""
sudo su postgres -c "psql -d onadata -c \"CREATE EXTENSION IF NOT EXISTS postgis;\""
sudo su postgres -c "psql -d onadata -c \"CREATE EXTENSION IF NOT EXISTS postgis_topology;\""

cd ~

virtualenv <.venv>
source <.venv>/bin/activate

cd onadata

cp onadata/settings/default_settings.py onadata/settings/local_settings.py

nano onadata/settings/local_settings.py

#set the password as in CREATE statement above

DATABASES = {
    'default': {
        # ...
        'PASSWORD': 'onadata',
        # ...
    }
}

#Add your public IP in ALLOWED_HOSTS if desired

ALLOWED_HOSTS = ['localhost', '123.456.78.90']

#change some settings as below: 

nano requirements/dev.pip

ipdb==0.10.2
ipython==5.3.0
#django-debug-toolbar

make

#Test your ona server first

python manage.py runserver 123.456.78.90:8000 --nothreading

#Ensure the log file exists
sudo touch /var/log/uwsgi/app/onadata.log

Enjoy!

**Comment by dev3320770** [comment]
@mwaigichuhi  i tried this but it didn't work

**Comment by mwaigichuhi** [comment]
@dev3320770 what exactly did you try?

**Comment by dev3320770** [comment]
@mwaigichuhi after following the commands on the above post from you, then i try to continue the installation with commands from this url  https://api.ona.io/static/docs/install.html but i couldnt continue it to run the application

**Comment by mwaigichuhi** [comment]
@dev3320770 I can only help if you are very specific about the failure or issue you have.

For instance, which OS environment are using, which command failed and can you show your error(s) here?

**Comment by dev3320770** [comment]
@mwaigichuhi  i did the installation on Ubuntu 14.04 LTS i followed the instructions you posted here and all the commands works but then after i run
python manage.py runserver 123.456.78.90:8000 --nothreading
and ensured that the log file exists
with this command sudo touch /var/log/uwsgi/app/onadata.log 
all worked.
Now im asking what happens after that?

what i did i continued with the instructions from  https://api.ona.io/static/docs/install.html.
Starting from
**# Compile api docs**
```
cd docs
make html
cd ..
```
**# Copy static files to static dir**
```
python manage.py collectstatic --noinput
python manage.py createsuperuser
```
I got stuck with the next commands since **script/etc** directory does not exist
i need help from there and after the installation hopefully i get to see something that looks like https://ona.io

**Comment by mwaigichuhi** [comment]
@dev3320770 

Please see below. 

create an upstart file for uwsgi to run onadata; /etc/init/onadata.conf

  #!upstart
  description "onadata upstart script"

  start on (local-filesystems and runlevel [2345])
  stop on runlevel [!2345]

  respawn

  script
      exec sudo /usr/local/bin/uwsgi --ini /opt/onadata-venv/uwsgi.ini --env DJANGO_SETTINGS_MODULE=onadata.settings.common
  end script

  pre-start script
      echo "[`date -u +%Y-%m-%dT%T.%3NZ`] Starting" >> /var/log/onadata_upstart.log
  end script

  pre-stop script
      echo "[`date -u +%Y-%m-%dT%T.%3NZ`] Stopping" >> /var/log/onadata_upstart.log
  end script

**Comment by mwaigichuhi** [comment]
Note: My uwsgi is in /home/webmaster/onadata/uwsgi so I made the change to point to it.

This is how the uwsgi.ini looks

[uwsgi]
http=:8000
socket=/home/webmaster/onadata/onadata.sock
chown-socket=www-data:www-data
chmod-socket=666
uid=webmaster
gid=www-data
chdir=/home/webmaster/onadata
module=onadata.apps.main.wsgi:application
master=True
processes=12
pidfile=/var/run/ona.pid
vacuum=True                 # clear environment on exit
harakiri=120                 # respawn processes taking more than 2 minute
max-requests=5000           # respawn processes after serving 5000 requests
logto=/var/log/uwsgi/app/onadata.log
virtualenv=/home/webmaster/virtualenv
static-map=/static=/home/webmaster/onadata/onadata/static
buffer-size=8192
#env=HTTPS=on
env=DJANGO_SETTINGS_MODULE=onadata.settings
stats=/home/webmaster/onadata/onastats.sock

**Comment by dev3320770** [comment]
@mwaigichuhi thank you so much , i will try that

**Comment by lincmba** [comment]
@dev3320770 is this still an issue?

**Comment by lincmba** [comment]
Closing this. Please reopen if needed.
