### ISSUE TITLE
SAV Exports failing due to duplicate name in the same choice list name

### ISSUE THREAD

**Issue by bmalina** [onaio/onadata#983]
Env Production

SAV Exports failing for a form due a duplicate name in the same choice list.

![image](https://cloud.githubusercontent.com/assets/20789710/24555849/41fb022c-163b-11e7-83bd-6ee0c23b9cc8.png)

CSV and Excel export working as expected.
Form can be accessed [here](https://ona.io/forcier_south_sudan/32199/190327#) 

Expected Results

SAV exports should ignore the duplicate and export as expected or give an error indicating the failure.

**Comment by moshthepitt** [comment]
Form where issue is reproducible: https://ona.io/acme/37113/230306#
